### ISSUE TITLE
"main" property inside bower.json seems to be set incorrectly

### ISSUE THREAD

**Issue by alterigor** [jakubroztocil/rrule#100]
Inside of bower.json file the "main" is set to "rrule.js", where it looks like it should be set to "lib/rrule.js". Because of this tools like wiredep that inject dependencies fail to inject the rrule.js as a dependency. Is it possible to change this in the bower.json?

**Comment by eliseumds** [comment]
:+1:

**Comment by jrhite** [comment]
👍

**Comment by davidgoli** [comment]
Fixed
