### ISSUE TITLE
Using integers in byweekday causes javascripterror in toText()

### ISSUE THREAD

**Issue by michaelkrog** [jakubroztocil/rrule#102]
This works:

``` javascript
var options = {"freq":"1", "byweekday":RRule.TU};
var rule = new RRule(options);
console.log(rule.toText());
```

This does not work:

``` javascript
var options = {"freq":"1", "byweekday":1};
var rule = new RRule(options);
console.log(rule.toText());
```

When calling `rule.toText()` the following exception is thrown:
`Uncaught TypeError: wday.getJsWeekday is not a function`

http://jsfiddle.net/17b1at32/2/

**Comment by mason505** [comment]
+1 im still seeing this bug

**Comment by splatEric** [comment]
I've just hit the same issue as well @michaelkrog is your fix suitable for a pull request into the main library?

**Comment by aratcliffe** [comment]
+1 I'm facing the same issue.

**Comment by rustinlewis** [comment]
Same issue here!

**Comment by ddorsett** [comment]
+1 still an issue: Uncaught TypeError: wday.getJsWeekday is not a function
Seems like there's activity again, maybe this will get fixed??

**Comment by johnlewiskalahari** [comment]
I found a way to work around this:

var myrule = {freq: RRule.weekly, byweekday[1,2,3]}
// myrule.toText() -- this crashes.
var myrule2 = rrulestr(myrule.toString());
// myrule.toText() -- this works.

It's a crappy solution though.

**Comment by davidgoli** [comment]
This appears fixed as of 2.3.4

**Comment by strass** [comment]
I got this error today until I converted the array of WeekdayStr into ints

**Comment by kevinrodriguez-io** [comment]
@strass Yes, effectively we need to use `Weekday.fromStr(your string)`
