### ISSUE TITLE
Constructor doesn't like its own defaults

### ISSUE THREAD

**Issue by tristanpendergrass** [jakubroztocil/rrule#104]
Not only does the `RRule()` constructor modify the options object passed in, but if you try to reuse that same options object, the new properties that have been added make it invalid.

See it all in this jsbin: https://jsbin.com/vicozufale/edit?js,console

For convenience, I'll copy the code to reproduce below.

``` javascript
  var params = {
    freq: RRule.WEEKLY
  };

  console.log(new RRule(params).toText()); // works
  console.log(new RRule(params).toText()); // no works
```

and the error thrown is 

```
Uncaught Error: Invalid options: bynmonthday, bynweekday
```

**Comment by jkbrzt** [comment]
Yes, the `options` object shouldn't be modified by the constructor. Also, the inconsistency is annoying (although mentioned here: https://github.com/jkbrzt/rrule#instance-properties).

**Comment by davidgoli** [comment]
This no longer repros as of 2.3.4
