### ISSUE TITLE
RRule undefined

### ISSUE THREAD

**Issue by grigio** [jakubroztocil/rrule#108]
Inside NPM webpack

``` javascript
var RRule = require('rrule').RRule;
// RRule is undefined

// This works
var RRule = require('rrule');
// or
import RRule from "rrule";
```

**Comment by arolson101** [comment]
I have the same problem.  Looks like there was an update a day or so ago but it's still broken :cry:

**Comment by jkbrzt** [comment]
How to fix that?

**Comment by arolson101** [comment]
In nlp.js I changed

```
if (serverSide) {
    RRule = require('./rrule').RRule;
```

to

```
if (serverSide) {
    RRule = require('./rrule');
```

but I don't think that's the whole story; in my webpacked project I have to do ```var RRule = require("rrule")``` instead of ```var RRule = require("rrule").RRule```

**Comment by jpmurray** [comment]
Anyone got this to work? I can get RRule to work, but I can't use `toText()` for the life of me :/

**Comment by nsb** [comment]
I'm having the same issue using webpack. I can't get nlp.js to work.

**Comment by nsb** [comment]
Ok, everything worked fine by using latest master.

**Comment by arolson101** [comment]
I think this issue is dead.  Please update if more support is needed!
