### ISSUE TITLE
Update rrule 

### ISSUE THREAD

**Issue by hx0day** [jakubroztocil/rrule#113]
bower.json until bower install  rrule
{
    "name": "rrule",
    "description": "JavaScript library for working with recurrence rules for calendar dates.",
    "homepage": "http://jakubroztocil.github.io/rrule/",
    "keywords": [
        "dates",
        "recurrences",
        "calendar",
        "icalendar",
        "rfc"
    ],
    "repository": {
        "type": "git",
        "url": "git://github.com/jakubroztocil/rrule.git"
    },

```
"version": "2.0.1",
"authors": [
    {
        "name": "Jakub Roztočil",
        "homepage": "http://subtleapps.com/"
    },
    {
        "name": "Lars Schöning"
    }
],
"main": "rrule.js", 
"ignore": [
    "**/.*",
    "node_modules",
    "components"
]
```

}

"main":"lib/rrule.js"

**Comment by arolson101** [comment]
I think this issue is dead.  Please update if more support is needed!
