### ISSUE TITLE
FREQ=MONTLY skips months that does not have same date.

### ISSUE THREAD

**Issue by michaelkrog** [jakubroztocil/rrule#114]
If I go to http://jkbrzt.github.io/rrule/ with my computer's date set to 2015-10-31 and choose FREQ=MONTHLY, then I get the following dates within the first year:

```
1   Sat Oct 31  2015    09:41:23    GMT+0100    (CET)
2   Thu Dec 31  2015    09:41:23    GMT+0100    (CET)
3   Sun Jan 31  2016    09:41:23    GMT+0100    (CET)
4   Thu Mar 31  2016    09:41:23    GMT+0200    (CEST)
5   Tue May 31  2016    09:41:23    GMT+0200    (CEST)
6   Sun Jul 31  2016    09:41:23    GMT+0200    (CEST)
7   Wed Aug 31  2016    09:41:23    GMT+0200    (CEST)
...
```

7 months out of 12. Other api's(fx. ical4j) gives dates like this:

```
20151031
20151130
20151230
20160130
20160229
20160329
20160429
20160529
20160629
20160729
20160829
20160929
20161029
```

Really, I think it should give the date of month which is closest to, but not higher than, seed date. Fx.:

```
20151031 (seed date)
20151130
20151231
20160131
20160229
20160331
20160430
20160531
20160630
20160731
20160831
20160930
20161031
```

**Comment by thiagotalma** [comment]
FREQ = MONTHLY means:
Monthly repeat in any 31.

If the month does not have 31, it is correct to rule that excludes this month.

Note that this rule differs from: always repeat the last day of the month.

**Comment by arolson101** [comment]
FYI I got an answer for this on stackoverflow: http://stackoverflow.com/questions/35757778/rrule-for-repeating-monthly-on-the-31st-or-closest-day.

In short, what you want to do is set ```bymonthday: [28, 29, 30, 31]``` and ```bysetpos: -1```

**Comment by davidgoli** [comment]
Unfortunately, this behavior conforms to the RRULE specification.
