### ISSUE TITLE
Know the 'duration' of the event

### ISSUE THREAD

**Issue by fatshotty** [jakubroztocil/rrule#115]
Hi,
I wonder: is there a way to know the duration of the event?
I'm using rrule to calculate the occurrences about some events. For example:
my event is "every 25th of the month"
I need to add other information in order to know the "duration" of my event. For example:
my event should be something like "every 25th of the month for 2 hours"
or
"every 25th of the month from 10.30am to 11.30am"

Thanks in advance

**Comment by thiagotalma** [comment]
http://www.ietf.org/rfc/rfc2445.txt

This project implements this RFC

**Comment by fatshotty** [comment]
Thanks for the quick reply.
I'm trying to pass DURATION key but RRule thows "Unknown RRULE property 'DURATION'" exception.
What is wrong?

Thanks

**Comment by thiagotalma** [comment]
As the project name suggests, the focus is close to the recurrence rule parameter.

The duration of the event is not included in this parameter.

See a complete example from Google Calendar:

```
BEGIN:VEVENT
DTSTART;TZID=America/Sao_Paulo:20151029T163000
DTEND;TZID=America/Sao_Paulo:20151029T173000
RRULE:FREQ=WEEKLY;COUNT=5;BYDAY=TH
DTSTAMP:20151027T162353Z
UIDfgb:co3urwe2njjebi75fdthr0s@google.com
CREATED:20151027T162153Z
DESCRIPTION:
LAST-MODIFIED:20151027T162153Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Im busy
TRANSP:OPAQUE
END:VEVENT
```

**Comment by NicksonYap** [comment]
Turns out RRULE a parameter used only for recurrence/repetition

Duration/Period is a separate paramter, in which for Google Calendar's case, DTSTART and DTEND represents a duration

**Comment by acro5piano** [comment]
@NicksonYap @fatshotty 
I've created `rrule-contrib`, which has duration support based on RRule. You can specify `start` and `end` with each timezone.

https://github.com/remotehour/rrule-contrib

Hope this helps.
