### ISSUE TITLE
Invalid options: byday

### ISSUE THREAD

**Issue by Nogginboink** [jakubroztocil/rrule#126]
I get the above error when attempting to parse the RRULE FREQ=YEARLY, BYMONTH=3, BYDAY=2SU. This RRULE is part of a VTIMEZONE in my ical file.

The error is thrown in line 454 of rrule.js. 

BYDAY is defined in section 4.3.10 of RFC2445. Are there any plans to implement this? I don't know of any way to determine if a given date/time is in standard time or daylight time without parsing out the VTIMEZONE.

**Comment by smhg** [comment]
You are passing the rules as an object? In that case you have to use `byweekday`.
`BYDAY` is only valid if you pass a string to `RRule.fromString()` or `rrulestr()`.
