### ISSUE TITLE
unsupported RDATE parm: VALUE=DATE

### ISSUE THREAD

**Issue by tchap** [jakubroztocil/rrule#127]
Trying to use `rrule` on Google Calendar events. The input value is

``` javascript
const recurrence = [
  'EXDATE;VALUE=DATE:20150909',
  'RRULE:FREQ=WEEKLY;BYDAY=TU,WE,TH'
];
```

When I run

``` javascript
const rule = rrulestr(_.join(recurrence, '\n'));
```

I get `unsupported RDATE parm: VALUE=DATE`.

**Comment by davidgoli** [comment]
This was addressed in #128. Please reopen if you are still having issues.
