### ISSUE TITLE
rrulestr not working when using npm install

### ISSUE THREAD

**Issue by shavenwalrus** [jakubroztocil/rrule#131]
I have done 'npm install rrule'. The files are downloaded in to node_modules, but the lib/rrule.js file is different from the one in the git repository.

Specifically, there is no export for rrulestr (or rruleset).

```
//=============================================================================
// Export
//=============================================================================

if (serverSide) {
    module.exports = {
        RRule: RRule
        // rruleset: rruleset
    }
}
if (typeof ender === 'undefined') {
    root['RRule'] = RRule;
    // root['rruleset'] = rruleset;
}

if (typeof define === "function" && define.amd) {
    /*global define:false */
    define("rrule", [], function () {
        return RRule;
    });
}
```

**Comment by bholbrook73** [comment]
It's also missing RRuleSet.

**Comment by DanielGSan** [comment]
When a update in npm repository to the current version? because is not the same version than here, few missing functions..

**Comment by davidfloegel** [comment]
Has there been any fix yet? Tried to use it tonight but no luck... :(

**Comment by paulxtiseo** [comment]
Same issue with on today's `npm install`. Should we expect a reply?

**Comment by karankapur3390** [comment]
Same issue today

**Comment by matheusramos** [comment]
Hey guys, I don't know if a new release is coming to npm, so, in the mean time, we can use `RRule.fromString("...");`

**Comment by davidgoli** [comment]
I believe this has been fixed. Let me know if there continue to be issues.
