### ISSUE TITLE
Wrong date calculation using after(new Date())

### ISSUE THREAD

**Issue by nvartolomei** [jakubroztocil/rrule#137]
``` javascript
const RRule = require('rrule').RRule;

console.log('current date: ', new Date());
// current date:  Sat Mar 26 2016 22:16:20 GMT+0200 (EET)

const rrule = RRule.fromString('FREQ=DAILY;BYHOUR=11;BYMINUTE=00');
const nextDate = rrule.after(new Date());

console.log('next date: ', nextDate);
// next date:  Mon Mar 28 2016 11:00:20 GMT+0300 (EEST)
```

It skips one day, if I move my calendar one day backwards the output is as expected.

**Comment by desmondmorris** [comment]
@nvartolomei I cannot replicate this one.  Were you able to resolve this?

**Comment by nvartolomei** [comment]
@desmondmorris the only way to replicate this was to set my calendar to the exact day and timezone in the comment above.

btw, i just ran this

```
const RRule = require('rrule').RRule;

const date = new Date('Sat Mar 26 2016 22:16:20 GMT+0200 (EET)')
console.log('current date: ', date);

const rrule = RRule.fromString('FREQ=DAILY;BYHOUR=11;BYMINUTE=00');
const nextDate = rrule.after(date);

console.log('next date: ', nextDate);
```

and the output is

```
current date:  2016-03-26T20:16:20.000Z
next date:  2016-10-19T08:00:41.000Z
```

shouldn't next date actually be March 27th? 

> **RRule.prototype.after(dt, inc=false)**
> Returns the first recurrence after the given Date instance. The inc argument defines what happens if dt is an occurrence. With inc == true, if dt itself is an occurrence, it will be returned.

**Comment by davidgoli** [comment]
@nvartolomei please confirm if this still repros under 2.3.4
