### ISSUE TITLE
new npm version release

### ISSUE THREAD

**Issue by kirrg001** [jakubroztocil/rrule#140]
Hey!

Right now i am using `jkbrzt/rrule#master` in my package.json.
Is the npm package ready for a new release?

Thanks!
Kate

**Comment by AntJanus** [comment]
The readme on NPM also has the wrong link to the demo app which is confusing.

**Comment by kirrg001** [comment]
+1

**Comment by balloob** [comment]
@jkbrzt it would be great if you could publish a new version. Even as is as a pre-release would be already great.

**Comment by arolson101** [comment]
FWIW I published what's available forked as ```rrule-alt``` and set it up on GitHub and npm.
see my comment here: https://github.com/jkbrzt/rrule/issues/160#issuecomment-268724051

**Comment by jakubroztocil** [comment]
Just released `2.2.0` — sorry for the wait! There have been no new changes since this issue was created so you should be able to just update your `package.json` to refer to this version instead of `master`.
