### ISSUE TITLE
Exrule and Exdate Support

### ISSUE THREAD

**Issue by audiolion** [jakubroztocil/rrule#143]
I see that in the 2.2.0-dev version EXRULE and EXDATE support was added. This is great because I was just writing workarounds for that today to handle RDATE, EXRULE and EXDATES. However, going through the code it looks like it just accepts the variant strings EXDATE/EXRULE/RDATE and applies the same processing, unless I am mistaken. This would mean an EXRULE for FREQ=ANUALLY;MONTH=12 would be naturally processed by nlp.js to be `Every December`. Shouldn't it render something like `Excluding Every December`?

**Comment by th3fallen** [comment]
@audiolion do you happen to have an example rule with an EXDATE in it?

**Comment by audiolion** [comment]
just tack on `EXDATE:19960402T010000Z` to a rule

**Comment by th3fallen** [comment]
@audiolion something like... `FREQ=DAILY;UNTIL=20170322T123144Z;BYDAY=WE;EXDATE: 19960402T010000Z `?

**Comment by th3fallen** [comment]
because no matter what format i pass it to the lib i cannot get it to parse which is why i was begging for an example to see what im formatting incorrectly.

**Comment by audiolion** [comment]
yeah that should be fine

**Comment by th3fallen** [comment]
tried doing 
`rrulestr('RRULE:FREQ=DAILY;UNTIL=20170322T123144Z;BYDAY=WE;EXDATE=20170322T050000Z');
` and get an error back

also tried 

`rrulestr('FREQ=DAILY;UNTIL=20170322T123144Z;BYDAY=WE;EXDATE=20170322T050000Z');`

am i missing something?

**Comment by audiolion** [comment]
Not sure, are you on 2.2.0 right? Without digging through the source code and debugging I couldn't tell you, that is a valid rrule string

**Comment by th3fallen** [comment]
yep on 2.2.0 thanks for the info though, what part of the lib are you using for yours? the `rruletr`?

**Comment by audiolion** [comment]
I actually was using this until I found out that the backend library I was using to store recurrence rules `django-recurrence` came with support for generating text versions of rules so I am no longer using this lib
