### ISSUE TITLE
UNTIL value in localtime (without 'Z') throws exception, fix?

### ISSUE THREAD

**Issue by arwarw** [jakubroztocil/rrule#145]
When using rrule.js (through InfCloud), my browser throws an exception

> Error: Invalid UNTIL value: 20160731T150000

This happens because my calendar (imported from Zarafa) contains a number of
RRULE: entries containing UNTIL values in localtime, yet rrule.js expects a
until-date to always end in 'Z' and be UTC. The appended PR fixes that
behaviour. Please note however, that your current implementation is strictly
adherent to RFC2445 which prescribes UTC time in the UNTIL part, my PR will
loosen that. Therefore I do not really know if one would want to accept this PR.

As suggested by the InfCloud developers, I will also report this bug to Davical, since that is the software currently supplying the described broken data to InfCloud.

**Comment by nigel-daniels** [comment]
I have the same issue when using an iCloud url the rrule code throws the following:

Error: Invalid UNTIL value: 20160730T115959
