### ISSUE TITLE
Passing in integer for byweekday yields incorrect toText()

### ISSUE THREAD

**Issue by abrahamguo** [jakubroztocil/rrule#153]
When integers are passed in to byweekday, `toText()` has strange behavior. The docs state that `0 == RRule.MO`; however, toText parses 1 as Sunday, and fails entirely on 0:

```
var rrule0 = new RRule({
  freq: RRule.WEEKLY,
  byweekday: 0
});

// "every week"; should say "every week on Monday"
alert(rrule0.toText());

// "FREQ=WEEKLY;BYDAY=MO"
alert(rrule0.toString());

var rrule1 = new RRule({
  freq: RRule.WEEKLY,
  byweekday: 1
});

// "every week on Monday"; should be "every week on Tuesday"
alert(rrule1.toText());

// "FREQ=WEEKLY;BYDAY=TU"
alert(rrule1.toString());
```

**Comment by rustinlewis** [comment]
I'm getting the same bug.  Has anyone be able to track this down?

**Comment by davidgoli** [comment]
This looks legitimate. `0` should be an acceptable substitute for `RRule.MO` as `1` is for `RRule.TU`.
