### ISSUE TITLE
new RRule mutates object passed in (v2.1.0)

### ISSUE THREAD

**Issue by kevlarr** [jakubroztocil/rrule#155]
Passing an options object into `new RRule` mutates that object.

Not a huge issue if you're creating it with just a literal object, but when you're using something persistent, say another RRule's `origOptions`, it will ruin that RRule's original options object forever after.

Basically, I want to be able to do **this**.

```
let opts = rrule1.origOptions;
opts.dtstart = someDate;

let rrule2 = new RRule(opts); // works
let rrule3 = new RRule(opts); // breaks
```

It works fine once, but when it runs again, `rrule1.options` has been mutated to a point that can't actually be parsed by `new RRule`.

Because `opts` has been mutated, I get the following error:

```
rrule.js:484 Uncaught Error: Invalid options: bynmonthday, bynweekday(…)
```

<img width="713" alt="screen shot 2016-09-08 at 3 04 49 pm" src="https://cloud.githubusercontent.com/assets/6306496/18362948/fa048822-75d5-11e6-9c92-6c213c732147.png">

**Comment by davidgoli** [comment]
It looks like this fix has been merged in, closing.
