### ISSUE TITLE
RRule.FR.clone(n) does not work

### ISSUE THREAD

**Issue by Adam-78** [jakubroztocil/rrule#156]
The following does not work:

```
`var myrule = new RRule({
        freq: RRule.MONTHLY,
        count: 7,
        byweekday: RRule.SU.clone(+1),
        bymonthday: [4]

    });`
```

tried the following `RRule.SU(+1)` and it does not work either. I get jquery error `TypeError: RRule.SU.clone is not a function`

**Comment by arolson101** [comment]
why do you think that ````RRule.SU``` is a function or has a clone method?  It's just a constant.  Try:
```js
var myrule = new RRule({
        freq: RRule.MONTHLY,
        count: 7,
        byweekday: RRule.SU,
        bymonthday: [4]

    });
```
