### ISSUE TITLE
Add backwards compatibility

### ISSUE THREAD

**Issue by sateffen** [jakubroztocil/rrule#159]
Hey,

in our usecase we use an older backend software, that expects the RRule in a little different way. It's described [here](http://icalendar.org/iCalendar-RFC-5545/3-3-10-recurrence-rule.html):

> Compliant applications MUST accept rule parts ordered in any sequence, but to ensure backward compatibility with applications that pre-date this revision of iCalendar the FREQ rule part MUST be the first rule part specified in a RECUR value.

I didn't see another issue mentioning this, but I think it's pretty cheap, but nice.

**Comment by davidgoli** [comment]
@sateffen If you'd still like this feature, I suggest opening a pull request. Thank you!
