### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by marcoancona** [jakubroztocil/rrule#160]
This is a good library, but it still has some problems (see the 68 open issues, npm not up to date) and limitations (eg. EXDATE, TZID field not supported). Since there are no new commits since February, I am wondering if this library is still maintained by the author.

**Comment by thathoo** [comment]
Not a lot of activity in the last one year. https://recordnotfound.com/rrule-jkbrzt-45496/activity I am inclined to say its not being actively maintained. But agree, a lot of good work has been done in this library!

**Comment by berlincount** [comment]
Coasted a bit through the forks, and there's a lot of good stuff there that'd totally be worth merging. Someone spending two days could make a serious dent, and a week would bring this library up to par and fix most of the issues people are addressing (e.g. working exdate & timezone support) centrally.

**Comment by arolson101** [comment]
I searched npmjs and found a couple forks but nothing indicating they would take over development, so I'm stepping up.

I forked the latest, patched in the good-looking (i.e. adds passing tests) pull requests, and published it on npm as ```rrule-alt```.  Github page is https://github.com/arolson101/rrule-alt

I'm trying to keep with the spirit of the original project in hopes that rrule development will once again resume and I can get rid of rrule-alt.

I'm not planning on doing any substantial development (e.g. timezone support) but will entertain pull requests that pass tests and are in spirit of the original.

**Comment by jakubroztocil** [comment]
@arolson101 thanks for your work! I've now released `master` as `2.2.0`. It would great to integrate your changes from `rrule-alt` to `rrule`.

**Comment by arolson101** [comment]
@jakubroztocil good to see you're back!

The only substantive changes I made were to merge the changes in pull requests #125, #128, #141, #146, and #158.  Also I added and updated a typescript definition file.

It might be easiest to just handle these pull requests yourself than for me to attempt to create one for all my changes (I have intermixed changes of 'rrule' to 'rrule-alt').  (I'm not very good at git stuff.)  If you're interested I can create a pull request for the definition file.

**Comment by http-teapot** [comment]
Any help needed to get the pull requests mentioned by @arolson101 merged in? I am particularly interested in #128.

**Comment by jakubroztocil** [comment]
Yes, I'm looking for people to help maintaining rrule!

**Comment by espen** [comment]
@jakubroztocil we use rrule.js in @MakePlans but as our usage is not very comprehensive I don't know the code that well but happy to help with some housekeeping with the more basic issues.

**Comment by jakubroztocil** [comment]
@espen great, I've invited you as a collaborator

**Comment by arolson101** [comment]
@jakubroztocil I’d be willing to help out and merge the changes I made in rrule-alt, and thus get rid of the fork

**Comment by jakubroztocil** [comment]
@arolson101 perfect! You're a collaborator now as well. 

I've also created a Gitter room for this project: https://gitter.im/rrule-js/

**Comment by Zizzamia** [comment]
Ciao @jakubroztocil! @http-teapot and I are working on a calendar app ([getplan.co](https://getplan.co/)) and we would love to fix and merge problems

**Comment by jakubroztocil** [comment]
@Zizzamia @http-teapot awesome. Added you as guys collaborators.

**Comment by arolson101** [comment]
I think we can close this issue out as "yes, still maintained"!

**Comment by espen** [comment]
awesome work @arolson101, thanks! 👏

**Comment by Zizzamia** [comment]
Great work @arolson101, I saw you update the version to `2.2.7`. 🔥 🚀 🌕
Do you need user permission from @jakubroztocil  to publish on **npm**?
The last release was [11 months ago](https://www.npmjs.com/package/rrule)

Also, one last thing, do you need help with creating **tags** and a  **CHANGELOG**, they are pretty straightforward I can help with that if you want.

**Comment by arolson101** [comment]
@espen thanks!
@jakubroztocil I need permission to publish on npm
@Zizzamia I would appreciate any help you can offer; I don't really know what I'm doing 🤷‍♂️

**Comment by jakubroztocil** [comment]
@arolson101 you should now be able to ship the new release on npm 🎉

**Comment by arolson101** [comment]
@jakubroztocil thanks! I was able to publish

**Comment by jakubroztocil** [comment]
@arolson101 awesome 🎉🚀

**Comment by jakubroztocil** [comment]
@arolson101 would you please list all the releases changes in the Changelog section of the readme?

**Comment by arolson101** [comment]
@jakubroztocil done
