### ISSUE TITLE
Apparently wrong 'between' results

### ISSUE THREAD

**Issue by quentinfasquel** [jakubroztocil/rrule#161]
With the following,
`var rule = new RRule("FREQ=WEEKLY;BYDAY=MO;BYHOUR=20;BYMINUTE=0;DTSTART=20161128T200000Z");
`

Printing my startDate and endDate used in "between()"
`2016-11-27T00:00:00.000Z 2017-01-08T00:00:00.000Z`

Gives me the output:
```
2016-12-05T19:00:00.000Z
2016-12-12T19:00:00.000Z
2016-12-19T19:00:00.000Z
2016-12-26T19:00:00.000Z
2017-01-02T19:00:00.000Z
```

On a first hand, I would expect 2016-11-28 to show up as well. On another hand, 19:00 isn't the time I requested, but 20:00 is expected for each result. I am sure I am missing something.

**Comment by arolson101** [comment]
daylight savings time, perhaps?

**Comment by arolson101** [comment]
Did you set ```inc```?

#### ```RRule.prototype.between(after, before, inc=false [, iterator])```
Returns all the occurrences of the rrule between after and before. The inc keyword defines what happens if after and/or before are themselves occurrences. With inc == true, they will be included in the list, if they are found in the recurrence set

As for the hour being off by one, I don't know.  It sounds like a daylight savings time issue but it's not DST right now.

**Comment by ibrychgo** [comment]
So, I'm very confused here. I have a similar problem in that I don't want to include today as an option for the next occurrence. But including "inc=false" as the second parameter for rule.next just throws an error that Inc doesn't exist. No matter what I do, it's including the current days occurrence. 

Can anyone shed some light into how "inc=False" can be used in a way that is valid Javascript?

**Comment by arolson101** [comment]
@ibrychgo could you show an example of the code that's throwing an error?

**Comment by ibrychgo** [comment]
Sure! Thanks for helping!
(sorry, for some reason, my line breaks aren't working below)

`var yesterday = moment.utc(today).subtract(1,'day').toDate();
var nextRepeat = rule.after(yesterday, inc=False);
`

**Comment by arolson101** [comment]
try
```
var yesterday = moment.utc(today).subtract(1,'day').toDate();
var nextRepeat = rule.after(yesterday, false);
```

**Comment by ibrychgo** [comment]
That doesn't throw an error, but it doesn't seem to have any effect on the
outcome. Whether true or false the result is the same.

I've been able to get around it though. :)  Thank you.

Bryan Lewis
Managing Partner

openmotive
3110 North Greenview Suite 600
Chicago, IL 60657

p+ 773.230.7122 | f+ 866.518.9854
bryan@openmotive.com <bryan@openmotive.com>

**Comment by JayantJoseph** [comment]
@ibrychgo @arolson101   I am also getting the same output whether or not **inc** equals _true_ or _false_, for the data given below:

**_startTime =>**  Mon Jul 01 2019 00:00:00 GMT+0530 (IST)
**_endTime =>**  Wed Jul 31 2019 00:00:00 GMT+0530 (IST)
**repeatRule =>**:  'RRULE:FREQ=WEEKLY'
let rule = rrulestr(repeatRule)
**rule =>**  { _cache: null,
      origOptions: { freq: 2, dtstart: undefined, tzid: undefined },
      options: 
       { freq: 2,
         dtstart: Tue Feb 26 2019 16:21:01 GMT+0530 (IST),
         tzid: null,
         interval: 1,
         wkst: 0,
         count: null,
         until: null,
         bysetpos: null,
         bymonth: null,
         bymonthday: [],
         bynmonthday: [],
         byyearday: null,
         byweekno: null,
         byweekday: [ 1 ],
         bynweekday: null,
         byhour: [ 10 ],
         byminute: [ 51 ],
         bysecond: [ 1 ],
         byeaster: null } }

**let repeatingDates** = rule.between(_startTime, _endTime, true)

**repeatingDates** => [ Tue Jul 02 2019 16:21:01 GMT+0530 (IST),
      Tue Jul 09 2019 16:21:01 GMT+0530 (IST),
      Tue Jul 16 2019 16:21:01 GMT+0530 (IST),
      Tue Jul 23 2019 16:21:01 GMT+0530 (IST),
      Tue Jul 30 2019 16:21:01 GMT+0530 (IST) ]

Why am I getting the output like this? Can you share how you worked around this @ibrychgo ??

**Comment by jacobg** [comment]
Common convention for ranges is to include start of range, but exclude end of range. It would be nice to see the capability here.
