### ISSUE TITLE
Incorrect Reoccurance

### ISSUE THREAD

**Issue by abuturla** [jakubroztocil/rrule#162]
I've noticed that for some weekly reoccurring events, the day of the event appears to be incorrect. For example, for the rule below it shows up on Google Calendar and Apple Calendar as occurring every Friday. However, rrule.js seems make the day of the reoccurrence based on what the current day of the week is. For example, the current day is a Monday, all events will occur on Monday's.

`RRULE:FREQ=WEEKLY;UNTIL=20170609T235959Z`

The easiest way to reproduce this is to go to the site below and enter the string above under the **RRULE string** tab.

http://jkbrzt.github.io/rrule/

**Comment by tn3rb** [comment]
I entered:
```
FREQ=WEEKLY;UNTIL=20180609T235959Z
```
(same as what you posted but without the `RRULE:` prefix)
at [http://jakubroztocil.github.io/rrule/](http://jakubroztocil.github.io/rrule/)
and all the events appear on Friday

**Comment by babenzele** [comment]
If there is not enough information to make a complete RRULE, the spec states that the missing parts are inferred from DTSTART. In this library, DTSTART defaults to `new Date`, which is where the missing BYDAY is getting populated from.
