### ISSUE TITLE
Error with "every friday"

### ISSUE THREAD

**Issue by devilbes** [jakubroztocil/rrule#163]
![2017-01-17 18 05 41](https://cloud.githubusercontent.com/assets/24765512/22028444/dd4c66ca-dcdf-11e6-8b10-ae87057857a8.png)

For any query **"Every friday**", in March instead of one of the **Fridays** are always issues **Thursday**!
anyone can help solve the problem?

thanks

**Comment by espen** [comment]
I'm unable to replicate this on master. Can you please provide a failing test?

**Comment by devilbes** [comment]
Yes, sure...
On your website in demo: https://jakubroztocil.github.io/rrule/:
Select the checkbox "byweekday" => "RRule.FR"...
And you see March 22 will issue Thursday
<img width="1421" alt="2018-01-16 19 58 56" src="https://user-images.githubusercontent.com/24765512/35004167-bbbfdef6-faf7-11e7-9773-c62aa6e32c93.png">

**Comment by espen** [comment]
Unable to replicate it. Might be DST issue though.

**Comment by devilbes** [comment]
@espen 
I understood the problem, this happens on the day when the clock is switched from daylight saving time from IST to IDT

**Comment by espen** [comment]
Yeah, there are some other issues dealing with DST so keeping this one closed.
