### ISSUE TITLE
Every n weekdays

### ISSUE THREAD

**Issue by stagha** [jakubroztocil/rrule#165]
I'm getting unexpected results when I try to build a rule for "every n weekdays" where n > 2.

**Every 3 weekdays**
`FREQ=DAILY;DTSTART=20170306T100000Z;COUNT=30;INTERVAL=3;WKST=MO;BYDAY=MO,TU,WE,TH,FR`

| What I expect | What RRule returns |
|:---------------|:---------------------|
| Mon, Mar 06, 2017 | Mon Mar 06, 2017 |
| Thu, Mar 09, 2017 | Thu, Mar 09, 2017 |
| Tue, Mar 14, 2017 | Wed, Mar 15, 2017 |
| Fri, Mar 17, 2017 | Tu, Mar 21, 2017 |
| Wed, Mar 22, 2017 | Fri, Mar 24, 2017 |

**Every 4 weekdays**
`FREQ=DAILY;DTSTART=20170306T100000Z;COUNT=30;INTERVAL=4;WKST=MO;BYDAY=MO,TU,WE,TH,FR`

| What I expect | What RRule returns |
|:---------------|:---------------------|
| Mon, Mar 06, 2017 | Mon Mar 06, 2017 |
| Fri, Mar 10, 2017 | Fri, Mar 10, 2017 |
| Thu, Mar 16, 2017 | Tue, Mar 14, 2017 |
| Wed, Mar 22, 2017 | Wed, Mar 22, 2017 |
| Tue, Mar 28, 2017 | Thu, Mar 30, 2017 |

I expect that when you count off, you would not count the Saturdays and Sundays. It looks like RRule counts the Saturdays and Sundays when coming up with its series of dates and removes them afterwards.

**Comment by moll** [comment]
I think the iCalendar spec states the interval is taken into account before the limiting by `BYDAY` in this `DAILY` case, so the output on the right column is correct. It also matches my independent RRULE implementation I use in my calendar. :)

**Comment by espen** [comment]
> If multiple BYxxx rule parts are specified, then after evaluating the specified FREQ and INTERVAL rule parts, the BYxxx rule parts are applied to the current set of evaluated occurrences in the following order: BYMONTH, BYWEEKNO, BYYEARDAY, BYMONTHDAY, BYDAY, BYHOUR, BYMINUTE, BYSECOND and BYSETPOS; then COUNT and UNTIL are evaluated. Here is an example of evaluating multiple BYxxx rule parts.
> 
> DTSTART;TZID=US-Eastern:19970105T083000 RRULE:FREQ=YEARLY;INTERVAL=2;BYMONTH=1;BYDAY=SU;BYHOUR=8,9; BYMINUTE=30
> 
> First, the "INTERVAL=2" would be applied to "FREQ=YEARLY" to arrive at "every other year". Then, "BYMONTH=1" would be applied to arrive at "every January, every other year". Then, "BYDAY=SU" would be applied to arrive at "every Sunday in January, every other year". Then, "BYHOUR=8,9" would be applied to arrive at "every Sunday in January at 8 AM and 9 AM, every other year". Then, "BYMINUTE=30" would be applied to arrive at "every Sunday in January at 8:30 AM and 9:30 AM, every other year". Then, lacking information from RRULE, the second is derived from DTSTART, to end up in "every Sunday in January at 8:30:00 AM and 9:30:00 AM, every other year". Similarly, if the BYMINUTE, BYHOUR, BYDAY, BYMONTHDAY or BYMONTH rule part were missing, the appropriate minute, hour, day or month would have been retrieved from the "DTSTART" property.

https://www.kanzaki.com/docs/ical/recur.html

So I think what @moll describes is correct.
