### ISSUE TITLE
since updating to release 2.2.0 RRule undefined error in our project

### ISSUE THREAD

**Issue by justbill2020** [jakubroztocil/rrule#166]
index.html imports rrule.js as it always has. 
```
 <script src="bower_components/rrule/lib/rrule.js"></script>
```
 

```
angular.js:14199 ReferenceError: RRule is not defined
    at parseICAL (service.js:132)
    at service.js:33
    at processQueue (angular.js:16696)
    at angular.js:16712
    at Scope.$eval (angular.js:17994)
    at Scope.$digest (angular.js:17808)
    at Scope.$apply (angular.js:18102)
    at done (angular.js:12082)
    at completeRequest (angular.js:12291)
    at XMLHttpRequest.requestLoaded (angular.js:12219)
(anonymous) @ angular.js:14199
(anonymous) @ angular.js:10707
processQueue @ angular.js:16704
(anonymous) @ angular.js:16712
$eval @ angular.js:17994
$digest @ angular.js:17808
$apply @ angular.js:18102
done @ angular.js:12082
completeRequest @ angular.js:12291
requestLoaded @ angular.js:12219
```

this just began with v2.2.0 please advice on how to resolve...

if it helps here's a link to our code... 

https://github.com/evancohen/smart-mirror/blob/dev/plugins/calendar/service.js#L132

you can see the lines 132 and lines 33 (which calls function parseICAL)

**Comment by justbill2020** [comment]
we reverted back to 2.1.0 in our bower.json file and this resolved it... however we would like to find the issue regardless so we can stick with the latest releases.

**Comment by davidgoli** [comment]
let me know if you're still having issues. Note the path for the import has changed, the new path should in README.md should be correct.
