### ISSUE TITLE
Timezone in UNTIL string should be optional

### ISSUE THREAD

**Issue by busybit** [jakubroztocil/rrule#169]
The timezone in UNTIL string should be optional. See RFC 2445 Chapter 4.3.12 Time.
https://www.ietf.org/rfc/rfc2445.txt

Make the "Z" in regex on line 194 optional.
change
var re = /^(\d{4})(\d{2})(\d{2})(T(\d{2})(\d{2})(\d{2})Z)?$/
to
var re = /^(\d{4})(\d{2})(\d{2})(T(\d{2})(\d{2})(\d{2})Z?)?$/

**Comment by zbozhilov** [comment]
Just encountered this issue with UNTIL date not in UTC time.
The suggested regex seems to fix this.

**Comment by Apollon77** [comment]
+1 encountered this too. Synology calendar also exports without Z at the end

**Comment by davidgoli** [comment]
I believe this can be closed. The regex has been updated as requested here.
