### ISSUE TITLE
add semicolon at the end of the rrule.js

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [jakubroztocil/rrule#171]
Wasn't able to concat to others libraries until added semicolon.
`"TypeError: (intermediate value)(...) is not a function"`
Apparently, it is a concating tool/version specific issue (for other project works fine), 
but it's so easy to have it fixed on your side :)

similar to this:
http://stackoverflow.com/questions/23370269/jquery-autosize-plugin-error-intermediate-value-is-not-a-function

**Comment by ariel-ibarra-jd** [comment]
I'm having the same issue

**Comment by balazsnemeth** [comment]
Me too!

**Comment by ariel-ibarra-jd** [comment]
@balazsnemeth I figured out that changing the order of your bower.json file and moving rrule to the bottom of the dependencies declarations can fix the issue.

**Comment by arolson101** [comment]
PR?

**Comment by mchapman** [comment]
I made a PR (#130) but it conflicts with the linting rules.  Bit of a Catch 22.

**Comment by arolson101** [comment]
PR is in
