### ISSUE TITLE
WKST - strange behavior

### ISSUE THREAD

**Issue by aureustaurus** [jakubroztocil/rrule#172]
I have options of rule like this:
![rrule-error-001](https://cloud.githubusercontent.com/assets/10784396/25271004/3ef6e14e-268b-11e7-9b8b-ec052ddd44f9.png)

after convert it to string, I have the rule like this:
`var newRruleString = 'FREQ=YEARLY;INTERVAL=2;COUNT=15;DTSTART=20170428T010000Z;BYDAY=MO,TU;BYMONTH=1,3;WKST=3'`
Where option **BYDAY** convert correct from number to MO,TU, and option **WKST** stay like number 3, but used the same weekdays options...
And after I try to create the rule from this string used:
`var rrule = RRule.fromString(newRruleString)`
I catch the error:
![rrule-error-002](https://cloud.githubusercontent.com/assets/10784396/25271025/5336c67e-268b-11e7-9e80-57ab1314ca2c.png)

in this code:
![rrule-error-003](https://cloud.githubusercontent.com/assets/10784396/25271028/599c6f1e-268b-11e7-8e9b-07b1e0dbdbf8.png)
![rrule-error-004](https://cloud.githubusercontent.com/assets/10784396/25271033/5e447a48-268b-11e7-9a55-578e1cf1d504.png)

Is it bug or feature or maybe should i create the `WKST=TH` manually? And why does code down? maybe should change condition `if (opts.wkst === null)` to ` if (!opts.wkst)` or something like this?
Thanks for the help

**Comment by espen** [comment]
Likely due to https://github.com/jakubroztocil/rrule/issues/110

**Comment by espen** [comment]
Closing in favour of #187. Reopen if this is another problem.
