### ISSUE TITLE
Using rrule on Angular 4 brings this error: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by aebmknrl** [jakubroztocil/rrule#174]
I import the library and  if i run RRULE then works, but rrulestr and rruleSet not works.

See my code:

```
...
import RRule from 'rrule';
import RRuleSet from 'rrule';
import rrulestr from 'rrule'
...
more code...
...
  console.log(rrulestr('RRULE:FREQ=MONTHLY;COUNT=5;DTSTART=20120201T023000Z'))
 
```
See the error:

![image](https://cloud.githubusercontent.com/assets/5152002/26279387/657fa9fc-3d80-11e7-9f80-a2862f3df0cd.png)

Can you help me?

**Comment by aebmknrl** [comment]
[http://plnkr.co/edit/xNo0uMar1UUTglxgbR4E?p=preview](url)

**Comment by AdamB37** [comment]
Getting same issue on Ember 2.6.0. @aebmknrl Broken link.

**Comment by arolson101** [comment]
incorrect usage- you're importing the RRule object every time.

From the docs:
```js
var RRule = require('rrule').RRule
var RRuleSet = require('rrule').RRuleSet
var rrulestr = require('rrule').rrulestr
```

which I believe should translate to
```js
import RRule, { RRuleSet, rrulestr } from 'rrule'
```
(but I'm not positive about the syntax)

**Comment by thefliik** [comment]
From my own usage, I believe it's
```
import { RRule } from 'rrule'

RRule.RRuleSet // to use RRuleSet
RRule // to use RRule

// I don't immediately remember how you access rrulestr
```
