### ISSUE TITLE
Why does Rrule has no endpoint of an event?

### ISSUE THREAD

**Issue by juergenweb** [jakubroztocil/rrule#177]
Most of the time an event has a start and and end point (fe. start at 2017-02-10 6am and end at 2017-02-10 8am). I am wondering why this is not implemented at rrule. It would be great to add such a possibility.

**Comment by stefanvds1** [comment]
@juergenweb it's simply not how iCal works. the duration of the event is taken from the DTSTART and DTEND difference (timespan) and then added to the startdate-time of each recurrence

**Comment by Nielio** [comment]
@stefanvds1 You are right, but rrule does't implement `DTEND` either. Only `until`, but this is a different thing.

**Comment by thefliik** [comment]
I think you’re asking for duration support, but I don’t think RRULE has that. You’d need to use a different library.

**Comment by acro5piano** [comment]
@thefliik
I've created `rrule-contrib`, which has duration support based on RRule. You can specify `start` and `end` with each timezone.

https://github.com/remotehour/rrule-contrib

Hope this helps.
