### ISSUE TITLE
Need Help with rrule string

### ISSUE THREAD

**Issue by first-noob** [jakubroztocil/rrule#179]
I'm pretty sure that I something misunderstood, but I didn't get the point. From the demo app, I got this as string: 
FREQ=WEEKLY;DTSTART=20170829T220000Z;COUNT=30;WKST=MO;BYMONTH=2 

If I try to use it with python-dateutil ( rrulestr() ) I have to rewrite this string to this: 

DTSTART:20170829T220000Z RRULE:FREQ=WEEKLY;COUNT=30;WKST=MO;BYMONTH=2 

Otherwise I get errors like: ValueError: unknown parameter 'DTSTART' Can someone point me to the right way? Why use the demo app string a " = " after DSTART, but in the examples of python-dateutil I see a colon " : " I'm really confused.

**Comment by mmngreco** [comment]
Hi @first-noob , I can't tell you what the correct implementation is. I would expect that if it's a standard you could use agnostically the language.

However, for your case, try the following:

````
from dateutil import rrule
rrule.rrulestr('DTSTART:20170829T220000Z\nFREQ=WEEKLY;COUNT=30;WKST=MO;BYMONTH=2')
```

I hope it's helpful.
