### ISSUE TITLE
rrule incorrect interpretation

### ISSUE THREAD

**Issue by neeryck** [jakubroztocil/rrule#180]
Given a rrule: FREQ=YEARLY;BYDAY=SA,SU;BYSETPOS=-1;BYMONTH=7;COUNT=4
The rrule demo construct the following object (from String tab): 
{
  freq: RRule.YEARLY,
  byweekday: [RRule.SA, RRule.SU],
  bysetpos: -1,
  bymonth: 7,
  count: 4
}

But it generate only sunday's dates on rule.all():

1	Sun 	Jul 	29 	2018 ...
2	Sun 	Jul 	28 	2019 ...
3	Sun 	Jul 	26 	2020 ...
4	Sat 	Jul 	31 	2021 ...

Please, it's a bug or I'm doing something wrong?
Thank you!

**Comment by Wakirin** [comment]
`FREQ=YEARLY;BYMONTH=7;BYDAY=SA,SU;COUNT=4`

```
1 | Sun | Jul | 01 | 2018 ...
2 | Sat | Jul | 07 | 2018 ...
3 | Sun | Jul | 08 | 2018 ...
4 | Sat | Jul | 14 | 2018 ...
```
What result you are expected ?

**Comment by neeryck** [comment]
FREQ=YEARLY;BYDAY=SA,SU;BYSETPOS=-1;BYMONTH=7;COUNT=4

The last Saturday and Sunday of July?!

**Comment by Wakirin** [comment]
`FREQ=YEARLY;BYDAY=-1SA,-1SU;BYMONTH=7`

**Comment by neeryck** [comment]
@Wakirin , thank you very much!
