### ISSUE TITLE
Got error: Unable to fully convert this rrule to text

### ISSUE THREAD

**Issue by vhmh2005** [jakubroztocil/rrule#182]
Below rrule is running fine but when I try to convert it to text, what I got is a string saying "Unable to fully convert this rrule to text". Please help

```
var rrule = require("rrule")
var rule = new rrule({
  freq: rrule.MINUTELY,
  interval: 5,
})

rule.toText()
```

**Comment by wlodi83** [comment]
Hello, I have the same problem MINUTELY frequency. Is there any workaround?

**Comment by espen** [comment]
MINUTELY and SECONDLY is currently not supported.

**Comment by davidgoli** [comment]
@vhmh2005 MINUTELY and SECONDLY have been supported since 2.2.8.
