### ISSUE TITLE
rrule - byweekday SU is generating SA only on Feb.

### ISSUE THREAD

**Issue by neeryck** [jakubroztocil/rrule#184]
Given a rrule: FREQ=MONTHLY;BYDAY=2SU,-2SU,-3SU;DTSTART=20171001T120000Z;WKST=SU;INTERVAL=1;BYMONTH=2;COUNT=10

The rrule demo construct the following object (from String tab):

{
  freq: RRule.MONTHLY,
  byweekday: [RRule.SU.nth(2), RRule.SU.nth(-2), RRule.SU.nth(-3)],
  dtstart: new Date(2017, 9, 1, 9, 0, 0),
  wkst: RRule.SU,
  interval: 1,
  bymonth: 2,
  count: 10
}

It generate on rule.all():

1	Sun 	Feb 	11 	2018 	09:00:00 	GMT-0200  ...
2	Sat 	Feb 	17 	2018 	09:00:00 	GMT-0200  ...
3	Sun 	Feb 	10 	2019 	09:00:00 	GMT-0200  ...
4	Sat 	Feb 	16 	2019 	09:00:00 	GMT-0200  ...
5	Sun 	Feb 	09 	2020 	09:00:00 	GMT-0200  ...
6	Sat 	Feb 	15 	2020 	09:00:00 	GMT-0200  ...
7	Sun 	Feb 	14 	2021 	09:00:00 	GMT-0200  ...
8	Sat 	Feb 	20 	2021 	09:00:00 	GMT-0200  ...
9	Sun 	Feb 	13 	2022 	09:00:00 	GMT-0200  ...
10	Sat 	Feb 	19 	2022 	09:00:00 	GMT-0200  ...

Shouldn't it generate only Sundays? In the other months it do the job correctly, this behave is only on Feb.
Please, it's a bug or I'm doing something wrong?
Thank you!

**Comment by espen** [comment]
I'm unable to replicate this using `"FREQ=MONTHLY;BYDAY=2SU,-2SU,-3SU;DTSTART=20171001T120000Z;WKST=SU;INTERVAL=1;BYMONTH=2;COUNT=10"`

**Comment by neeryck** [comment]
Did it occur to you that it might be a timezone problem? I changed my timezone to Argentina and the problem didn't happen. The problem  occured only in Brasilia timezone (GMT-3). It's a bug, isn't it?

**Comment by espen** [comment]
@neeryck that's possible, there are issues with DST and timezones using this lib. Keeping this issue closed as there are other open issues with those problems.
