### ISSUE TITLE
How to set an all-day rule with date-format DTSTART?

### ISSUE THREAD

**Issue by leeqiang** [jakubroztocil/rrule#186]
I want to set an all-day rule, just like
```
FREQ=DAILY;INTERVAL=6;`DTSTART=20170101`;WKST=MO'
```

The DTSTART format must be date, but only allow date-time. 

How?

**Comment by espen** [comment]
Yes, DTSTART is currently converted to date-time.

**Comment by leeqiang** [comment]
@espen Do you have plan to resolve this issue?

**Comment by espen** [comment]
@leeqiang pull requests are welcome :)

**Comment by leeqiang** [comment]
@espen Got it.

**Comment by leeqiang** [comment]
@espen #192

**Comment by arolson101** [comment]
I am unclear what problem this solves.  Why not put in the extra 0s?

**Comment by espen** [comment]
Well DATE is a valid data type. And if you want a list of dates then getting a full DATETIME isn't the correct output.

But I'm not sure this is the best way to solve this. There shouldn't be a need to specify allDay as a boolean, it should be based on the value being either DATE or DATETIME type I think.
