### ISSUE TITLE
isLeapYear breaks when using Cypress or other testing framework which replaces native Date object

### ISSUE THREAD

**Issue by Aali13265** [jakubroztocil/rrule#197]
isLeapYear uses instanceof to determine whether the argument is a Date object or an integer. Testing frameworks such as Cypress (which I believe in turn uses SinonJS functionality) can replace the native Date object which makes the instanceof check fail. The argument is then treated as an integer and suddenly every year is a leap year, causing weekly recurrence rules to stop prematurely once March rolls around.

Example:
`cy.clock() // set time to January 1st, 1970`
`const rrule = RRule.fromString('FREQ=WEEKLY;DTSTART=20180214T093000Z;INTERVAL=1;UNTIL=20180429T220000Z;BYDAY=TH')`
`rrule.all().length => 3`

vs

`//cy.clock()`
`const rrule = RRule.fromString('FREQ=WEEKLY;DTSTART=20180214T093000Z;INTERVAL=1;UNTIL=20180429T220000Z;BYDAY=TH')`
`rrule.all().length => 11`

Replacing `if (year instanceof Date)` with `if (year.getFullYear)` fixes the problem, although from a quick look at how the function is used it seems the more hygienic fix of creating a separate function to deal with Date objects is also possible.

**Comment by arolson101** [comment]
could you submit a PR?
