### ISSUE TITLE
missing/duplicate days

### ISSUE THREAD

**Issue by ghost** [jakubroztocil/rrule#201]
Hi guys, could you please help me, i have the following options for rrule constructor, for some reason, when i do ` rule.between( oneDayBehindNow(),  nextYear() ) ` i have all dates except on November Thursday 1, 2018; Moreover i have duplicate date on October 28, 2 dates object with same value.  
Thank you very much for great tool, please point me out in right direction, what i'm doing wrong ? Thank you.

```
{
byeaster:null
byhour:[12]
byminute:[30]
bymonth:null
bymonthday:Array(0)
bynmonthday:Array(0)
bynweekday:null
bysecond:[0]
bysetpos:null
byweekday:null
byweekno:null
byyearday:null
count:null
dtstart:Sat Mar 10 2018 12:30:00 GMT+0100 (W. Europe Standard Time)
freq:3
interval:1
until:null
wkst:0
}
```
![error](https://user-images.githubusercontent.com/29680495/37243336-dc7add2c-2477-11e8-87db-225931b12a1e.jpg)

**Comment by chrishanyu** [comment]
See #209
