### ISSUE TITLE
RRule.MONTHLY is not working

### ISSUE THREAD

**Issue by sajinshrestha** [jakubroztocil/rrule#204]
Current version **v2.2.0**

dtstart - `10/02/1997` returns -  10/02/1997, 11/01/1997 and 12/02/1997. 

![image](https://user-images.githubusercontent.com/1527385/38180833-f02e0aea-35f4-11e8-90c4-d40283a0531f.png)

dtstart - both dates `11/02/1997` and `12/02/1997` yield same results. 

![image](https://user-images.githubusercontent.com/1527385/38179572-b46313ac-35ea-11e8-858d-b7c1099bf3e0.png)

Github [Demo](https://jakubroztocil.github.io/rrule/) ***updated a year ago***  shows correct results

![image](https://user-images.githubusercontent.com/1527385/38180658-dd7f498c-35f3-11e8-9824-a5c3be32f7d7.png)

**Comment by davidgoli** [comment]
This should work as of RRule 2.3.4.
