### ISSUE TITLE
Rule breaks when FREQ=DAILY with Hourly or Minutes

### ISSUE THREAD

**Issue by DigitalThoughts** [jakubroztocil/rrule#205]
I get no output. This will be the case, whenever daily with hour or minutes are entered.

var rule = RRule.fromString("FREQ=DAILY;WKST=MO;DTSTART=20180412T050900Z;BYHOUR=3");
rule.toText()

fails to produce the rule string.

![bug](https://user-images.githubu
sercontent.com/15922855/38666226-0e61c0dc-3e5c-11e8-9b41-aa668e2cc45a.png)

**Comment by harrisi** [comment]
The `byhour` field is expecting to be an array. If you're able to construct the object with the `RRule()` constructor, this will work (with `byhour: [3]`).

**Comment by davidgoli** [comment]
This no longer reproduces as of 2.3.4. `rule.toText()` here produces the result `'every day at 3'`.
