### ISSUE TITLE
Cannot redeclare block-scoped variable 'RRule'.

### ISSUE THREAD

**Issue by sudosandwich3** [jakubroztocil/rrule#208]
I'm getting 4 of these errors in typescript 2.6.2:

[at-loader] ./node_modules/@types/rrule/index.d.ts:16:10 
    TS2451: Cannot redeclare block-scoped variable 'RRule'. 

[at-loader] ./node_modules/@types/rrule/index.d.ts:17:11 
    TS2451: Cannot redeclare block-scoped variable 'RRule'. 

[at-loader] ./node_modules/rrule/index.d.ts:17:10 
    TS2451: Cannot redeclare block-scoped variable 'RRule'. 

[at-loader] ./node_modules/rrule/index.d.ts:18:11 
    TS2451: Cannot redeclare block-scoped variable 'RRule'.

**Comment by davidgoli** [comment]
@sudosandwich3 Are you able to repro with the latest version (2.3.0)?

**Comment by davidgoli** [comment]
Please reopen if you are still experiencing issues.
