### ISSUE TITLE
Confusion about using a "sequence" in byweekday

### ISSUE THREAD

**Issue by mesqueeb** [jakubroztocil/rrule#210]
For **Byweekday** the docs say:
> a sequence of integers, one of the weekday constants (RRule.MO, RRule.TU, etc), or a sequence of these constants. 

Do you mean an `array`? The word "sequence" isn't often used in JS and it's quite confusing imo.

BTW, If my array is eg. `['MO','TH']` I get `BYDAY=THundefined;`
Is this a bug?

**Comment by davidgoli** [comment]
Try:

```js
const rrule = new RRule({
      dtstart: new Date(Date.UTC(2010, 2, 3)),
      count: 10,
      byweekday: [RRule.MO, RRule.TH]
    }).toString()
// => "DTSTART=20100303T000000Z;COUNT=10;BYDAY=MO,TH"
```

I believe the term "sequence" was originally borrowed from the Python, which has multiple "sequence" types (list, tuple, etc.) In JS, it just means Array.
