### ISSUE TITLE
WEEKLY rule produces wrong dates in Chrome/React Native under some timezones

### ISSUE THREAD

**Issue by Matherunner** [jakubroztocil/rrule#214]
### Bug

When working under the Singapore timezone (UTC+0800), given the following rule

```javascript
const rrule = new RRule({
  dtstart: new Date(2018, 5, 6, 10, 0, 0),
  freq: RRule.WEEKLY,
  count: 3,
});
```

when running in Chrome/React Native, `rrule.all()` gives

```
Tue Jun 12 2018 10:00:00 GMT+0800 (Singapore Standard Time)
Tue Jun 19 2018 10:00:00 GMT+0800 (Singapore Standard Time)
Tue Jun 26 2018 10:00:00 GMT+0800 (Singapore Standard Time)
```

which are obviously incorrect, because the specified `dtstart` (2018-06-06) lies on a Wednesday.

When running on Safari/NodeJS, it produces the correct dates, which are 2018-06-06, 2018-06-13, and 2018-06-20.

### Cause

The `ORDINAL_BASE` is defined to be at 1900-01-01:

```javascript
ORDINAL_BASE: new Date(1900, 0, 1),
```

Under Safari/NodeJS, the `Date` constructor interprets this date to be specified under the **current** Singapore timezone of UTC+0800. That is, the constructed `Date` object points to **1900-01-01, 00:00:00 at UTC+0800**, or **1899-12-31, 16:00:00 at UTC time**.

However, Chrome/React Native interprets the argument to be a date under the **Singapore timezone in 1900**, which is [06:55:25 ahead of UTC](http://www.math.nus.edu.sg/aslaksen/teaching/timezone.html). That is, the constructed `Date` points to **1900-01-01, 00:00:00 at UTC+0655**, or **1899-12-31, 17:04:35 at UTC time**.

Unfortunately, the timezone offset of 06:55:25 is precise to a second. When `fromOrdinal` is called, it relies on `getTimezoneOffset` of `ORDINAL_BASE`, which is precise only to a minute. The second-precision is therefore lost, and this results in `fromOrdinal` returning incorrect dates.

### Workaround

We could change the date of `ORDINAL_BASE`, or remove the timezone accounting in `fromOrdinal` as suggested by [raphaelm here](https://github.com/jakubroztocil/rrule/issues/157#issuecomment-377179204). Though I have not tested if these workarounds would create other bugs.

**Comment by kadiocat** [comment]
There are problems with time zones  from +3 to +13. The rest work fine

**Comment by AkselsLedins** [comment]
@Matherunner We are experiencing the same bug in GMT+2

**Comment by giapnhtadi** [comment]
Same here with GMT+7, and GMT+9, 2.2.0 works :(

**Comment by davidgoli** [comment]
This is probably fixed now? Please let me know if you're still able to reproduce.
