### ISSUE TITLE
rrulestr is missing from TypeScript definitions

### ISSUE THREAD

**Issue by hgezim** [jakubroztocil/rrule#216]
Code:

```
import { RRule, RRuleSet, rrulestr } from 'rrule';
```

Error:

`error TS2305: Module '"...node_modules/rrule/index"' has no exported member 'rrulestr'.`

**Comment by Zizzamia** [comment]
Thank you @kourge for adding more types!
cc @hgezim @arolson101

**Comment by davidgoli** [comment]
@arolson101 any updates on when this might be merged?
