### ISSUE TITLE
Issue with Monthly rrule

### ISSUE THREAD

**Issue by skyskyskyblue** [jakubroztocil/rrule#231]
I am using 2.2.9v. It seems it cannot show the past time.
Today is 02/08/2018, if I use the string:
"DTSTART=20180802T000000Z;FREQ=MONTHLY;BYMONTHDAY=2;BYSETPOS=-1"
the results are:
        "2018-09-02T00:00:00.000Z",
        "2018-10-02T00:00:00.000Z",
        "2018-11-02T01:00:00.000Z",
        "2018-12-02T01:00:00.000Z",
        "2019-01-02T01:00:00.000Z",
        "2019-02-02T01:00:00.000Z",
        "2019-03-02T01:00:00.000Z",
        "2019-04-02T00:00:00.000Z",
        "2019-05-02T00:00:00.000Z",
        "2019-06-02T00:00:00.000Z",
                  ..............
without 2018-08-02.

What I expect is including today (2018-08-02).
But it seems it works fine on the website.

**Comment by davidgoli** [comment]
@skyskyskyblue can you please show the rrule code you're using to generate this? (eg `all`, `between`, etc)

**Comment by davidgoli** [comment]
The times here are also showing the issue in #233

**Comment by skyskyskyblue** [comment]
```
const rule = rrulestr(rulestring);
const now = new Date();
const currentyear = now.getFullYear();
const infiveyears = new Date().setFullYear(currentyear + 5);
return {
                dates: rule.between(now, infiveyears, true),
           };
```

I see the problem:
I am using "now = new Date()" that means from the current time to 5 years later.
Sorry for the confusion.

**Comment by davidgoli** [comment]
Please reopen if you are still having issues.
