### ISSUE TITLE
Can no longer install with npm

### ISSUE THREAD

**Issue by OmniPotent42** [jakubroztocil/rrule#239]
When I try to install this package, it only installs a README, a package.json, and a LICENSE file. Is Yarn now the only way I can install this package, or is there a workaround to let me still use npm?

**Comment by arolson101** [comment]
@davidgoli

**Comment by davidgoli** [comment]
@arolson101 I don't have npm publish privileges, and it appears something went wrong with the publish step

**Comment by davidgoli** [comment]
FWIW yarn, npm, and conventional download should all work with this package as of 2.3.0.

**Comment by arolson101** [comment]
@davidgoli I think it has to do with package.json's ```files``` property:
```json
  "files": [
    "lib",
    "README.md"
  ]
```

**Comment by davidgoli** [comment]
@arolson101 ah yes, that would do it! nice catch

**Comment by arolson101** [comment]
published 2.3.1

**Comment by davidgoli** [comment]
@arolson101 I'm not seeing this fixed. I pulled down 2.3.1 and am still seeing missing `dist/` folder in spite of the change to `package.json`.

**Comment by davidgoli** [comment]
https://docs.npmjs.com/files/package.json#files

> The optional files field is an array of file patterns that describes the entries to be included when your package is installed as a dependency. File patterns follow a similar syntax to .gitignore, but reversed: including a file, directory, or glob pattern (*, **/*, and such) will make it so that file is included in the tarball when it's packed. 

> Certain files are always included, regardless of settings:

package.json
README
CHANGES / CHANGELOG / HISTORY
LICENSE / LICENCE
NOTICE
The file in the "main" field

Since we aren't seeing the file in the "main" field (`dist/es6`), I'm wondering if there might be some other factor at work...

**Comment by davidgoli** [comment]
@arolson101 feel free to email me: david@substantial.com

**Comment by davidgoli** [comment]
@arolson101 I don't have the ability to publish on my own. Can you please add me as a maintainer?
