### ISSUE TITLE
Compilation error when using Typescript 3.0.1 and rrule 2.3.2

### ISSUE THREAD

**Issue by thomasvidas** [jakubroztocil/rrule#244]
I'm getting this error when running a fairly basic `tsconfig.json` and `tsc`

```
node_modules/rrule/dist/es6/rruleset.d.ts:48:5 - error TS2416: Property 'clone' in type 'RRuleSet' is not assignable to the same property in base type 'RRule'.
  Type '() => RRuleSet' is not assignable to type '() => RRule'.
    Type 'RRuleSet' is not assignable to type 'RRule'.
      Types have separate declarations of a private property '_iter'.
```

I dug into the types and you can
- remove `private _iter;` from `dist/rruleset.d.ts` 
- replace `private _iter;` with `protected _iter: any;` in `dist/rrule.d.ts`

**Comment by davidgoli** [comment]
@thomasvidas Addressed by #245

**Comment by davidgoli** [comment]
@thomasvidas Deployed in 2.3.3

**Comment by thomasvidas** [comment]
Awesome! Thanks for the quick fix
