### ISSUE TITLE
Dates near DST transitions are off by a day

### ISSUE THREAD

**Issue by tn3rb** [jakubroztocil/rrule#249]
My apologies if this is still a duplicate of an existing issue.
There were some older issues that maybe appeared to be similar, but those were supposedly fixed by #235. 

Current issue is that generated dates are off by a day when hitting a DST transition.
I'm located in British Columbia Canada and my current system time is `Fri Aug 10 15:59:11 PST 2018` and the upcoming transition from Pacific Summer Time to Pacific Standard Time occurs at the end of Sat Nov 03 2018 (or the beginning of Sun Nov 04 2018 ???). 

The issue can be demonstrated via the following:

```js
// Every week on Monday, Wednesday, Friday for 4 times, starting Nov 1, 2018
const ruleString = 'DTSTART=20181101T120000Z;FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,WE,FR;COUNT=4;WKST=SU';
const rrule = RRule.fromString( ruleString );
// just to show that string is being parsed correctly
console.log( 'rrule.toString():', rrule.toString() );
// generate datetimes
console.log( rrule.all() );
```

produces:

```
rrule.toString(): DTSTART=20181101T120000Z;FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,WE,FR;COUNT=4;WKST=SU
Array(4) [
  0: Date 2018-11-02T12:00:00.000Z    // Fri Nov 02 2018 05:00:00 GMT-0700 (Pacific Summer Time)
​  1: Date 2018-11-04T13:00:00.000Z    // Sun Nov 04 2018 05:00:00 GMT-0800 (Pacific Standard Time) 
​  2: Date 2018-11-06T13:00:00.000Z    // Tue Nov 06 2018 05:00:00 GMT-0800 (Pacific Standard Time)
  ​3: Date 2018-11-09T13:00:00.000Z    // Fri Nov 09 2018 05:00:00 GMT-0800 (Pacific Standard Time)
]
```

The second date (Sun Nov 04) Should be Monday the 5th, and the third date (Tue Nov 06) should be Wednesday the 7th, so both of those dates have been moved a day earlier despite the times still appearing to be correct. What's especially disturbing is that the Tue Nov 6th date is getting bumped back a day despite not even being directly on the DST transition. 

### Expected Results

Considering the `BYDAY` settings only allow for Mondays, Wednesdays, and Fridays, I would expect to see the following dates:

```
Array(4) [
  0: Date 2018-11-02T12:00:00.000Z    // Fri Nov 02 2018 05:00:00 GMT-0700 (Pacific Summer Time)
​  1: Date 2018-11-05T13:00:00.000Z    // Mon Nov 05 2018 05:00:00 GMT-0800 (Pacific Standard Time)
​  2: Date 2018-11-07T13:00:00.000Z    // Wed Nov 07 2018 05:00:00 GMT-0800 (Pacific Standard Time)
  ​3: Date 2018-11-09T13:00:00.000Z    // Fri Nov 09 2018 05:00:00 GMT-0800 (Pacific Standard Time)
]
```

### Versions

- RRule 2.3.3
- OS: Windows 10
- Browser Versions: Chrome 67.0.3396.99 and FF 62.0b13

Anyways, I hope that helps you isolate the issue, and just wanted to give everybody involved with this a huge thanks for all of the time, effort, and talent that went into producing this library. It is greatly appreciated.

**Comment by davidgoli** [comment]
@tn3rb Can you try too reproduce this with 2.3.4 (just published)? It may address the "off by 1 day" issue.

**Comment by tn3rb** [comment]
HA! Ya didn't noticed that you published that behind my back there !!! :)
Will do asap

**Comment by tn3rb** [comment]
is there anyway to confirm the RRule version via command line?

**Comment by davidgoli** [comment]
@tn3rb Hm, can you confirm that you actually upgraded to 2.3.4? I just added a test with your specific code and pushed to Travis, and added a build with the `America/Vancouver` time zone, but it appears that all timezones are showing the exact same (correct) dates. See: https://github.com/jakubroztocil/rrule/pull/250/files#diff-bf37b808d44432356cff284f57b6c7fc

**Comment by davidgoli** [comment]
You can check your installed version with:

```
$ yarn list rrule
```

**Comment by tn3rb** [comment]
hmmmm...

```
 npm list rrule
-- rrule@2.2.9
```

wonder if some other package is setting that...
I'm directly using https://github.com/Fafruch/react-rrule-generator and bumped the version in its package.json to 2.3.4 
but console is telling me something otherwise...

kk well that gives me hope that the fix is as easy as getting the current version running...
will report back asap

**Comment by davidgoli** [comment]
Often with semver you won't automatically get minor version package upgrades unless you explicitly run `npm upgrade rrule@^2.3.4`

**Comment by tn3rb** [comment]
dang it... nah I had an old library still on the system that I had been testing out and it was specifying 2.2.9, so I think my system was then downgrading to that
removed that lib, re-installed, and 

# BOOM

working now

thanks so much for your help and patience

**Comment by davidgoli** [comment]
👍 glad to hear it's working now!
