### ISSUE TITLE
What happened to the dist/es6 folder

### ISSUE THREAD

**Issue by zhex900** [jakubroztocil/rrule#270]
Hi,

What happened to the `dist/es6` folder?

It was there not long ago. After I did new install of rrule, es6 is gone. 

`es6` was removed from `2.3.6`

**Comment by zhex900** [comment]
Sorry, I saw this 
https://github.com/jakubroztocil/rrule/pull/260

**Comment by zhex900** [comment]
Hi,

I am running cypress with rrule. 

Since es6 is moved to esm. My tests have a build issue. It is still looking for es6 folder. 
`Error: Cannot find module '../../../node_modules/rrule/dist/es6' from `
Is there a way to solve this?

**Comment by davidgoli** [comment]
@zhex900 I'm not sure what might be happening for you, nothing in our distribution package references that folder? Could it be something you have cached locally?
