### ISSUE TITLE
rule.toString() output is completely broken in 2.5.1

### ISSUE THREAD

**Issue by SystemParadox** [jakubroztocil/rrule#273]
I've just installed 2.5.1 from npm and the output from `rule.toString()` seems to be completely broken:

```
var RRule = require('rrule').RRule;

const rule = new RRule({
      freq: RRule.WEEKLY,
        interval: 5,
        byweekday: [RRule.MO, RRule.FR],
        dtstart: new Date(Date.UTC(2012, 1, 1, 10, 30)),
        until: new Date(Date.UTC(2012, 12, 31))
});
console.log(rule.toString());
```

Expected output (works in 2.4.1):

```
FREQ=WEEKLY;INTERVAL=5;BYDAY=MO,FR;DTSTART=20120201T103000Z;UNTIL=20130131T000000Z
```

Actual output (2.5.0 and 2.5.1):

```
DTSTART:20120201T103000Z
RRULE:FREQ=WEEKLY;INTERVAL=5;BYDAY=MO,FR;UNTIL=20130131T000000Z
```

I've noticed a rather disturbing message in the commits about updating to match the RFC and breaking everything (https://github.com/jakubroztocil/rrule/commit/b458e6198d77e855d5ad8fe28f4759928ff04bd3).

1. What is the rationale behind changing this? Are you really planning to support the full multi-line format defined in the RFC?
2. Why, why why why **OH WHY** haven't you bumped the major version number!?!!?!?!!!!!???? :sob:

**Comment by davidgoli** [comment]
@SystemParadox The output has indeed changed, but the old (legacy) strings should still be correctly parsed. What exactly are you finding broken? The old syntax did not conform to the RFC, and the new one does.

**Comment by davidgoli** [comment]
Oh, I can see how using string equality to validate your rrules would break in that case. However, I don't think eg. the ordering of the properties in the rrule was ever guaranteed to be consistent either. I suppose I assumed that conformance to the RFC 5545 that this package promises to deliver was the API this was supposed to document. I did have the PR in question open for over 2 weeks before merging, and didn't get any comments, but I know that it's not obvious to everyone interested when such PRs are up for review. At this point I'm the only active maintainer pushing code for the past few months and don't have anyone with much historical context here weighing in, so I didn't know what functionality people were depending on exactly. I was planning much bigger breaking changes for 3.0, and was taking pains to ensure the library continued to operate with its own output, but could not make guarantees on what other code was doing with that output. At the end of the day, pushing that code was the only way to see what was going to break. I'm genuinely sorry it broke things for you!

At this point, if you need string equality with older output, I recommend reverting to the 2.3.x series, as 2.4 introduced timezone support and also a breaking bug in serializing that timezone support.  I don't have a ton of time or QA support on this project outside of automated tests, so I'm relying on existing tests to tell me when I've broken functionality in a backwards-incompatible way, but that's probably not complete enough, but it's what I have to work with at this point!

Thanks for reporting your issue and again, I'm sorry this broke things for you. My next non-trivial bugfix release will be a 3.0.

**Comment by SystemParadox** [comment]
Yes I'm naively splitting on `;` and `=` and sorting by the keys (and sometimes excluding some like `DTSTART`). At the time it seemed like it would be simpler and more robust than naming every property, but this was perhaps a mistake.

Your work on this project is definitely very much appreciated! Sorry for complaining! I was mainly trying to understand the reason for the change and where the project is headed.

I would like to help so please feel free to give me a mention if there's anything you would like me to take a look at.

Thanks.

**Comment by davidgoli** [comment]
@SystemParadox would an implementation of `rrule.equals(otherRule)` give you what you need? theoretically, 2 rrules are equal if their `origOptions` objects are deeply equal.

If I had to write this library from scratch it would definitely be functional and immutable, and there would be no large classes with RRULE, instead just functions that accept options objects and/or strings, so I'm inclined to lean toward that direction.

**Comment by SystemParadox** [comment]
That would be excellent, although the slight wrinkle is that sometimes I also need to be able to check for equality but ignore DTSTART and/or UNTIL. I'll leave you to decide if that kind of complication is worth having. I have no objection to having to implement that myself.

Isn't `origOptions` just the original options passed to the constructor? One of the issues I've had is dealing with the default options. For example, `FREQ=WEEKLY;INTERVAL=1` is equivalent to `FREQ=WEEKLY`, because `INTERVAL=1` is the default. In this case their origOptions are not equal, even though the rules are equivalent.

It would be very useful to have some sort of normalisation, so that options set to default values just disappear. I don't know if it would be possible to put this in transparently without causing compatibility issues, or if it would have to be a separate rrule.normalise() method.

**Comment by irnnr** [comment]
Can we revert the behavior to NOT prefix the rule toString() output with "RRULE"? This could be done as a bugfix with in the 2.5.x range to restore previous behavior. If you want to (re)add the prefix, it can be done in 3.0.
