### ISSUE TITLE
rrule 2.5.5 doesn't seem compatible with gCal API anymore

### ISSUE THREAD

**Issue by kevin-abl** [jakubroztocil/rrule#278]
Between 2.4.1 and 2.5.5, our app stopped being able to create new events in Google Calendar API.

The code looks something like this:

```
recurrence: [`RRULE:${new RRule({
					freq: RRule.WEEKLY,
					byweekday: [0,1,2],
					until: '2018-09-18T06:59:00Z'
				}).toString()}`],
```

Is there something I need to change in the new version?  We haven't changed our side in a year.

**Comment by davidgoli** [comment]
@kevin-abl You no longer need to wrap the output in '`RRULE:`'; `toString()` should give you exactly what you need. If you aren't finding that to work, please paste the output of `new RRule(...).toString()` here. Thanks!

**Comment by davidgoli** [comment]
@kevin-abl Closing this, please reopen if you're still having trouble

**Comment by irnnr** [comment]
This prefixing is/was causing issues for us, too since it changes behavior significantly. We used to add the prefix on our side, now they get double prefixed and ical.js failed to parse them.

You should have bumped the major version for this change.
