### ISSUE TITLE
.between() impacted by daylight savings

### ISSUE THREAD

**Issue by lancedolan** [jakubroztocil/rrule#279]
### Reporting an issue

Thank you for taking an interest in `rrule`! Please include the following in
your report:

- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [x] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.
- [x] Expected output
- [x] Actual output
- [x] The version of `rrule` you are using
  - 2.3.6 and 2.5.5.   I'm only 90% sure I saw it in 2.5.5 as well.
- [x] Your operating system
  - MacOS, Android, and iOS (It's a react-native app)
- [x] Your local timezone (run `$ date` from the command line
  of the machine showing the bug)
  - CDT, will become CST in a couple months, as seen in the example below...

The `.between()` function shows when a date will be in the future without adjusting for daylight savings time. EG. If you have an event daily at midnight, the `.between()` results would be correct if the people attending that event pretended daylight savings never happened and just continued with the same 24 hour repetition and attended at a time that would _actually_ be 11pm in the new daylight savings offset. 

Hack script to reproduce. This code shows an event which should happen on the first monday of each month.

```
const ruleString = "FREQ=MONTHLY;BYDAY=1MO"
const RRule = require('rrule').RRule;
let options = RRule.parseString(ruleString);
let from = new Date();
// make midnight...
from.setHours(0)
from.setMinutes(0)
from.setSeconds(0)
options.dtstart = from
let rRule = new RRule(options);
let until = new Date(new Date().setMonth(new Date().getMonth() + 3));
rRule.between(new Date(), until).map(eventOcurrence => {
console.log("Created " + eventOcurrence)
})
```

Expected output:
```
Created Mon Oct 01 2018 00:00:00 GMT-0500 (CDT)
Created Mon Nov 05 2018 00:00:00 GMT-0600 (CST)
Created Mon Dec 03 2018 00:00:00 GMT-0600 (CST)
```

Observed output:
```
Created Mon Oct 01 2018 00:00:00 GMT-0500 (CDT)
Created Sun Nov 04 2018 23:00:00 GMT-0600 (CST)
Created Sun Dec 02 2018 23:00:00 GMT-0600 (CST)
```

**Comment by lancedolan** [comment]
Here is the hacky crap we're doing to get around it

```
... 
rRule.between(new Date(), until).map(eventOcurrence => {
  const offsetDiff = eventOcurrence.getTimezoneOffset() - from.getTimezoneOffset()
  if (offsetDiff!=0) {
    eventOcurrence.setTime(eventOcurrence.getTime() + (offsetDiff * 60000))
  }
  console.log("Created " + eventOcurrence)
})
```

**Comment by davidgoli** [comment]
@lancedolan please reopen if this doesn't solve your problem

**Comment by evoactivity** [comment]
@davidgoli This does not seem to solve the problem.

Given this rule
```
DTSTART:20180912T110000
RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=WE;WKST=MO
```
and these dates passed to .between()
start = 2018-09-12
end = 2018-11-12

between returns Tuesday 30th October as a repeat date when it should be Wednesday 31st Ocotber

this is on rrule 2.5.5

**Comment by davidgoli** [comment]
@evoactivity Please confirm you're using the correct approach, using only UTC dates. With UTC dates, I do not see the behavior you're describing:

```
> const rule = RRule.fromString('DTSTART:20180912T110000Z\nRRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=WE;WKST=MO')
> rule.between(new Date(Date.UTC(2018, 8, 12)), new Date(Date.UTC(2018, 10, 12)))

[ 2018-09-12T11:00:00.000Z,
  2018-09-19T11:00:00.000Z,
  2018-09-26T11:00:00.000Z,
  2018-10-03T11:00:00.000Z,
  2018-10-10T11:00:00.000Z,
  2018-10-17T11:00:00.000Z,
  2018-10-24T11:00:00.000Z,
  2018-10-31T11:00:00.000Z,
  2018-11-07T11:00:00.000Z ]
```

**Comment by evoactivity** [comment]
Hm, I can't reproduce it in an isolated environment, I'll do more digging when I'm back on that project. I'll post my findings here to let you know.

**Comment by timruo** [comment]
I meant to leave this comment here:

https://github.com/jakubroztocil/rrule/issues/293#issuecomment-433086318
