### ISSUE TITLE
infinitie itteration when interval is 0

### ISSUE THREAD

**Issue by Fredrik-Oberg** [jakubroztocil/rrule#287]
When trying to iterate over `rrule` that has `interval` set to 0  the iteration be in a endless loop. 

`rrulestr('FREQ=YEARLY;INTERVAL=0;BYSETPOS=1;BYDAY=MO').count()` will never end.

The case for me was that we have an input that outputs a `rrulstr` to be parsed with `rulestr()`and this input could have `INTERVAL=0`. This behavior crashed the page.

The culprit is here https://github.com/jakubroztocil/rrule/blob/master/src/iter.ts#L199 this will never add to count if interval is 0. 

Version:  2.5.6
Os: macOS High Sierra 10.16.3
Timezone: `Thu Oct  4 08:17:53 CEST 2018`

- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [x] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.
- [x] Expected output
- [x] Actual output
- [x] The version of `rrule` you are using
- [x] Your operating system
- [x] Your local timezone (run `$ date` from the command line
  of the machine showing the bug)

**Comment by davidgoli** [comment]
Resolved by #288 .
