### ISSUE TITLE
Problem with Weekly RRule when local date is different from UTC date

### ISSUE THREAD

**Issue by RonyDimebag** [jakubroztocil/rrule#290]
Hi,

I saw some resembling bugs reported that were closed, or noted that simply reverting back to v2.2.0 fixed the problem, I'm reporting this to help fix this since I had to revert back to 2.2.0 as well and I think it would be a pity to be stuck in an older version without new features.

I've been using latest version (v2.5.6), running a quite simplistic RRule - _FREQ=WEEKLY;BYDAY=TU_.
Generally it works well, but when my local time is between midnight (00:00) and 2am, which makes my local date different than UTC date (I'm in GMT+0200), all the instances I received by calling a _between_ function fall under Wednesdays.

As mentioned, reverting back to v2.2.0 fixed this problem.

Hope this helps and thanks for all your contribution.
Rony

**Comment by davidgoli** [comment]
@RonyDimebag do you have specific code you might be able to share on how to reproduce this?

Generally there is no advantage whatsoever to using local dates, period. You should be able to do everything you need with floating dates (UTC) + tzid. But let me know if you've got code that shows an edge case that isn't being handled.

**Comment by RonyDimebag** [comment]
Hi David,

I do use UTC, the error persists regardless, depending on my local timezone as described.
I tried using tzid as well but with no success, only reverting back to v2.2.0 solved this.

The code is as simple as it can get - 

`var nrule = RRule.rrulestr('FREQ=WEEKLY;BYDAY=TU');
nrule.options.dtstart = <some date in the past>;
var results = nrule.between(new Date(start * 1000), new Date(end * 1000), true);`

_start_ and _end_ are usually the beginning and end of the month, the result I receive is many instances occurring on Wednesdays.
To reproduce this properly change your machine timezone to GMT+0200 and set the local time to anywhere between midnight and 2am.

**Comment by davidgoli** [comment]
@RonyDimebag I'm an unable to reproduce; I'm only getting instances on Tuesdays. Can you please give me the exact values you're using for `dtstart`, `start`, and `end`?

**Comment by davidgoli** [comment]
What I do see is that `between` is calculating the hour, minute, and second in UTC which I think may be what you're seeing. You may fix this for now in 2.5.6 by adding `BYHOUR=0;BYMINUTE=0;BYSECOND=0` to your rrule string. I think a case could be made that these should default to whatever hour, minute, second are passed in to `dtstart` or at least 0.

**Comment by davidgoli** [comment]
@RonyDimebag Ah, I think I see the bug, which is that this:

```ts
const nrule = rrulestr(`DTSTART:20180701T070000
    RRULE:FREQ=WEEKLY;BYDAY=TU`);

// or

const nrule = new RRule({
  byweekday: Days.TU,
  dtstart: new Date(Date.UTC(2018, 6, 1)),
  freq: Frequency.WEEKLY,
})
```

behaves differently from this:

```ts
const nrule = rrulestr(`FREQ=WEEKLY;BYDAY=TU`)
nrule.options.dtstart = new Date(Date.UTC(2018, 6, 1));
```

For your purposes, you should be able to switch to either of the first two versions, but for now, you should consider the `options` property of an existing RRULE to be immutable (ie, don't change it after you've created the rrule). If you want to change the `options` of an existing RRule, you should create a new RRule from an existing `options` object like so:

```ts
const newOptions = {
   ...nrule.options,
   dtstart: ...
}

const newRule = new RRule(newOptions)
```

**Comment by davidgoli** [comment]
There's going to be a rewrite of the interfaces in 3.0 to move the RRule interface away from the original Python model (which is very poorly designed IMO) and toward a functional/immutable style. Until then, you have the workarounds I mentioned above. Please reopen if you have a use case not covered by them. Thanks!

**Comment by RonyDimebag** [comment]
Thanks a lot @davidgoli !
