### ISSUE TITLE
EXDATE not working with dst

### ISSUE THREAD

**Issue by harryy2510** [jakubroztocil/rrule#292]
### Scenario

- RRuleSet starting from 20th october till 18th November in timezone America/Los_Angeles
- DST begins on 2nd November 2018 2am
- Added two EXDATE on 1st november and 7th november

### Expectation

- EXDATE on 1st november in PDT and 7th november in PST
- Should exclude 1st november and 7th november from the array of result

### Reality

- 1st november is excluded but 7th november is not.
- If 7th november is added in PDT, it works.

### RRuleSet

DTSTART;TZID=America/Los_Angeles:20181022T070000 RRULE:FREQ=WEEKLY;INTERVAL=1;UNTIL=20181118T075959;WKST=SU;BYDAY=MO,TU,WE,TH,FR EXDATE;TZID=America/Los_Angeles:20181101T070000,20181107T080000

**Comment by davidgoli** [comment]
I converted your report into the following test case:

```ts
  it('puts EXDATEs in the correct offset regardless of DST', () => {
    const set = rrulestr(`DTSTART;TZID=America/Los_Angeles:20181022T070000
    RRULE:FREQ=WEEKLY;INTERVAL=1;UNTIL=20181118T075959;WKST=SU;BYDAY=MO,TU,WE,TH,FR
    EXDATE;TZID=America/Los_Angeles:20181101T070000,20181107T070000`) as RRuleSet

    expect(
      set.between(
        new Date(Date.UTC(2018, 9, 31)),
        new Date(Date.UTC(2018, 10, 9))
        )
    ).to.deep.equal([
      new Date(Date.UTC(2018, 9, 31, 7)),
      new Date(Date.UTC(2018, 10, 2, 7)),
      new Date(Date.UTC(2018, 10, 5, 7)),
      new Date(Date.UTC(2018, 10, 6, 7)),
      new Date(Date.UTC(2018, 10, 8, 7)),
    ])
  })
```

This test passes for me, which is expected. What difference are you expecting to see? I think it makes perfect sense that the time is given as 0700 regardless of DST.

**Comment by davidgoli** [comment]
@harryy2510 I believe the library is working as expected, please reopen if you have a test case not covered by the above explanation.

**Comment by harryy2510** [comment]
<img width="1680" alt="screenshot 2018-10-21 at 6 34 55 am" src="https://user-images.githubusercontent.com/7416971/47262062-8b13a380-d4fb-11e8-9a22-6fe06e119775.png">

@davidgoli  I agree to the point that if the recurrence is at 7pm, it will remain at 7pm whether or not dst and the EXDATE should be too 7pm. But the case I am trying to explaing is, while in DST, the UTC time will change as 8pm instead of 7pm.


- 7pm in America/Los_Angeles on 30th October is 2am 31st UTC

`moment().tz('America/Los_Angeles').month(9).date(30).hour(19).minute(0).second(0).millisecond(0).toISOString()` will result in `2018-10-31T02:00:00.000Z`

- 7pm in America/Los_Angeles on 10th November is 3am 11th UTC

`moment().tz('America/Los_Angeles').month(10).date(10).hour(19).minute(0).second(0).millisecond(0).toISOString()` will result in `2018-11-11T03:00:00.000Z`


While parsing the rule, the UTC time itself is adjusted during dst. so should the EXDATE should also resemble to adjusted time?


`const rruleSet = new RRuleSet();
    rruleSet.exdate(new Date(moment(this.event.start).startOf('d').toISOString()));`

This is the piece of code I am using for setting the EXDATE which gives me the result with two different offsets depending on standard or dst time.

**Comment by harryy2510** [comment]
@davidgoli It's too tricky to be easily understandable. Can you help me with a little piece of code?
 
Let me know if you are free for a few minutes and we can discuss it somewhere where I can exactly show you the problem.

**Comment by davidgoli** [comment]
Closing due to resolution via chat.
