### ISSUE TITLE
Example ` between` returns the wrong values?

### ISSUE THREAD

**Issue by cjrd** [jakubroztocil/rrule#297]
- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [x] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.

From the `between` example in `Readme.md`:
```javascript
const rrule = require("rrule")
const RRule = rrule.RRule

const rule = new RRule({
  freq: RRule.WEEKLY,
  interval: 5,
  byweekday: [RRule.MO, RRule.FR],
  dtstart: new Date(Date.UTC(2012, 1, 1, 10, 30)),
  until: new Date(Date.UTC(2012, 12, 31))
})

console.log(rule.between(new Date(Date.UTC(2012, 7, 1)), new Date(Date.UTC(2012, 8, 1))))
```

- [x] Expected output
`[ 2012-06-18T10:30:00.000Z, 2012-06-22T10:30:00.000Z ]`
- [x] Actual output
`[ 2012-08-27T10:30:00.000Z, 2012-08-31T10:30:00.000Z ]`

- [x] The version of `rrule` you are using
`2.5.6`

- [x] Your operating system
```bash
$ cat /proc/version
# Linux version 4.4.0-1062-aws (buildd@lgw01-amd64-046) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #71-Ubuntu SMP Fri Jun 15 10:07:39 UTC 2018
```
- [x] Your local timezone (run `$ date` from the command line
  of the machine showing the bug)
`Tue Nov  6 19:55:26 UTC 2018`

**Comment by davidgoli** [comment]
The actual output looks correct to me. Keep in mind that:

```node
> new Date(Date.UTC(2012, 7, 1))
2012-08-01T00:00:00.000Z
> new Date(Date.UTC(2012, 8, 1))
2012-09-01T00:00:00.000Z
```

**Comment by davidgoli** [comment]
If you want the dates in your given "expected output", you want to do:

```js
      rule.between(
        new Date(Date.UTC(2012, 5, 1)),
        new Date(Date.UTC(2012, 6, 1))
      )
```
