### ISSUE TITLE
Wrong next date when selecting WEEKLY options

### ISSUE THREAD

**Issue by tamvanvo** [jakubroztocil/rrule#299]
I configured the rrule options for WEEKLY, but for some reasons, rrule calculates wrong next date.
Please see the images:
![Wrong next date 1](https://user-images.githubusercontent.com/32564233/48613005-1e39df00-e9bd-11e8-9781-f92d977550ab.PNG)
![Wrong next date 2](https://user-images.githubusercontent.com/32564233/48613029-314caf00-e9bd-11e8-9beb-42d5f0f6080c.PNG)

And I configured some times, it works as expected.
![Correct next date](https://user-images.githubusercontent.com/32564233/48613127-72dd5a00-e9bd-11e8-81c0-7197ea4b9ac9.PNG)

Is it a bug?
Thanks

**Comment by davidgoli** [comment]
Would you mind attaching code samples in text form and not screenshots, please? Much easier to copy/paste into a test. Thank you!

**Comment by davidgoli** [comment]
@tamvanvo Is it a bug? Yes and no.

It's the same issue as #300, which is essentially confusion about how this library returns dates. See https://github.com/jakubroztocil/rrule#important-use-utc-dates for more clarification and #300 for discussion.
