### ISSUE TITLE
2.2.8 to 2.5.6 - Browser support

### ISSUE THREAD

**Issue by peteringram0** [jakubroztocil/rrule#302]
Hi All, 

between 2.2.8 and 2.5.6 something has changed on the browser support (I have tests within my project and from a rrule point of view all my tests pass on version 2.2.8 and version 2.5.6 just fine). However targeted does not run on 2.5.6. I cant give much info on the target hardware but i have no console errors / logs. Im hoping someone knows if there have been dropped browsers between these two versions so i can work out what i need to polyfill.

Thanks

**Comment by davidgoli** [comment]
We did introduce a lot of ES6/babel tooling around 2.3. Without knowing your browser specs, I can't help you much more than that. Good luck!

**Comment by peteringram0** [comment]
For anyone finding this who is facing similar issue its due to the Luxon import.

https://github.com/moment/luxon/blob/master/docs/matrix.md
