### ISSUE TITLE
I created a `parseICalString()` function which might be useful to rrulejs

### ISSUE THREAD

**Issue by thefliik** [jakubroztocil/rrule#304]
*This is just an FYI in case you find it useful*

I made an [improved ical string parsing function](https://gitlab.com/john.carroll.p/rschedule/tree/master/packages/ical-tools) which may be useful for rrulejs. It's in a self-contained npm package with no dependencies: `@rschedule/ical-tools` ([the function is less than 1kb gzipped](https://bundlephobia.com/result?p=@rschedule/ical-tools@0.0.1), though feel free to also copy-paste the function into rrulejs).

Basically, rather than simply parsing the "rrule" pieces of an iCAL string (which I think is all rrulejs can currently handle?), it parses the entire ICAL string (including `VCALENDAR` / `VEVENT` / etc components) and returns a javascript object for further manipulation.

This is all the function does. It does not attempt to validate the string against the ical spec (for example, if the `VEVENT` object had two `DTSTART` properties, which is forbidden by the spec, `parseICalString()` would return an object with a DTSTART property of length 2 (i.e. `DTSTART: [{...}, {...}]`). RRulejs would need to decide how it wanted to consume the output of `parseICalString()`. 

Example:

```typescript
const VEVENT_STRING =
`BEGIN:VEVENT
DTSTART;TZID=Europe/London:20181008T090000
DTEND;TZID=Europe/London:20181008T093000
RRULE:FREQ=DAILY
DTSTAMP:20181010T134444Z
UID:31k86s3g7aim1hp6og8kvuuvh9@google.com
CREATED:20181008T120947Z
DESCRIPTION:
LAST-MODIFIED:20181008T120947Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Event repeating Daily at 9am
TRANSP:OPAQUE
END:VEVENT`;

parseICalString(VEVENT_STRING) === {
  componentName: 'ROOT',
  BEGIN: [{
    componentName: 'VEVENT',
    RRULE: [{
      propertyName: 'RRULE',
      propertyValue: 'FREQ=DAILY',
    }],
    DTSTART: [{
      propertyName: 'DTSTART',
      propertyValue: '20181008T090000',
      TZID: 'Europe/London',
    }],
    DTEND: [{
      propertyName: 'DTEND',
      propertyValue: '20181008T093000',
      TZID: 'Europe/London',
    }],
    DTSTAMP: [{
      propertyName: 'DTSTAMP',
      propertyValue: '20181010T134444Z',
    }],
    UID: [{
      propertyName: 'UID',
      propertyValue: '31k86s3g7aim1hp6og8kvuuvh9@google.com',
    }],
    CREATED: [{
      propertyName: 'CREATED',
      propertyValue: '20181008T120947Z',
    }],
    DESCRIPTION: [{
      propertyName: 'DESCRIPTION',
      propertyValue: '',
    }],
    "LAST-MODIFIED": [{
      propertyName: 'LAST-MODIFIED',
      propertyValue: '20181008T120947Z',
    }],
    LOCATION: [{
      propertyName: 'LOCATION',
      propertyValue: '',
    }],
    SEQUENCE: [{
      propertyName: 'SEQUENCE',
      propertyValue: '0',
    }],
    STATUS: [{
      propertyName: 'STATUS',
      propertyValue: 'CONFIRMED',
    }],
    SUMMARY: [{
      propertyName: 'SUMMARY',
      propertyValue: 'Event repeating Daily at 9am',
    }],
    TRANSP: [{
      propertyName: 'TRANSP',
      propertyValue: 'OPAQUE',
    }],
  }],
}
```

### Feel free to close this.

**Comment by davidgoli** [comment]
This looks awesome! Thanks, @thefliik ! I'll probably use this in the 3.0 rewrite.
