### ISSUE TITLE
Custom attributes / parameters

### ISSUE THREAD

**Issue by rogierverbrugge** [jakubroztocil/rrule#306]
Hi, thanks for creating this lovely tool for recurring dates.

I was wondering if I can include some unique_id/event_id for the event in my rruleset. Can't find it in any of the issues but I need it to open an "edit window" for all the dates in the rrule.all() or rrule.between() output.

Hope someone can help me out.

**Comment by davidgoli** [comment]
Sounds like you want to track some metadata alongside the rrule. This is outside the scope of this library; you might want to design your data model like so:

```js
{
  event_id: 123,
  rule: 'DTSTART:...\nRRULE:...',
}
```
