### ISSUE TITLE
Returned dates are not reflecting tzid, are reflecting dtstart's timezone offset.

### ISSUE THREAD

**Issue by reggi** [jakubroztocil/rrule#307]
I am setting a `dtstart` to `America/New_York` in `september` which has an offset of `04` and I am getting a date in `december` which  should have an offset of `05`. For some reason the `tzid` is not being used to apply the correct timezone to the dates returned from the rule.

```js
import * as assert from 'assert';
import * as moment from 'moment-timezone';
import { RRule } from 'rrule';

const tzid = 'America/New_York';

const rule = new RRule({
  tzid,
  freq: RRule.DAILY,
  interval: 1,
  byweekday: [RRule.WE],
  dtstart: moment('2018-09-01').tz(tzid).toDate(),
  until: null,
});

const day = moment('2018-12-11').tz(tzid).toDate();
const date = rule.after(day);
const expectedDate = moment('2018-12-12').tz(tzid).toDate();
console.log({date}) // { date: 2018-12-12T04:00:00.000Z }
console.log({expectedDate}) // { expectedDate: 2018-12-12T05:00:00.000Z }

// this should pass but is throwing an exception because the offset is incorrect.
assert.equal(moment(date).isSame(moment(expectedDate)), true);
```

**Comment by davidgoli** [comment]
@reggi This isn't really an rrule issue. Rather, you have created a _local date_ using Moment when you should have created a date using `Date.UTC` as shown in the README.

Really, I'd strongly suggest, in general, moving away from Moment and toward its replacement, [Luxon](https://moment.github.io/luxon/)

**Comment by reggi** [comment]
@davidgoli all of my `moments`are being converted to javascript dates. The bug still applies. 

```js
import { RRule } from 'rrule';

const tzid = 'America/New_York';

const rule = new RRule({
  tzid,
  freq: RRule.DAILY,
  interval: 1,
  byweekday: [RRule.WE],
  dtstart: new Date('2018-09-01T04:00:00.000Z'),
  until: null,
});

console.log(rule.after(new Date('2018-12-11T05:00:00.000Z')));
```

This is outputting `2018-12-12T04:00:00.000Z` which has the wrong time offset for New York because of daylight savings.

**Comment by reggi** [comment]
Ok I think I get it, you can't put in time information?
