### ISSUE TITLE
Timezone not reflected without use of TZ environment variable

### ISSUE THREAD

**Issue by reggi** [jakubroztocil/rrule#308]
```js
import { RRule } from 'rrule';

const rule = new RRule({
  tzid: 'America/New_York',
  freq: RRule.DAILY,
  interval: 1,
  byweekday: [RRule.WE],
  dtstart: new Date(Date.UTC(2018, 8, 1)),
  until: null,
  count: 20,
});

console.log(rule.after(new Date(Date.UTC(2018, 11, 11))));
```

When I run this code with out `TZ="UTC"` the timestamp has no timezone data.

```
node  ./example.js
2018-12-12T00:00:00.000Z
```

When I run this code with `TZ="UTC"` the timestamp has timezone data.

```
TZ="UTC" node  ./example.js
2018-12-12T05:00:00.000Z
```

Is there a way within the rule for this to be consistent regardless of what the TZ environment variable is set to? So that it still applies the set `tzid` and output to `T05:00:00.000Z`.

Is there any documentation for the `TZ` environment variable?

**Comment by davidgoli** [comment]
`TZ` is part of the Linux/Mac OS operating system: https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html

You probably don't want to use the `tzid` param at all. Try removing it and see if that gives you the result you want.

**Comment by davidgoli** [comment]
Also read about _floating times_ here: https://icalendar.org/iCalendar-RFC-5545/3-8-3-1-time-zone-identifier.html

This is all the the README for this repo.
