### ISSUE TITLE
Incorrect DTSTART in RRuleSet

### ISSUE THREAD

**Issue by MBach** [jakubroztocil/rrule#309]
I'm trying to do some complex event splitting and I'm stuck with the following use case.

* I have a RRuleSet like this: 
`DTSTART:20181218T070000Z RRULE:BYDAY=TU;FREQ=WEEKLY`
This is owned by someone called Manager

Another person, called a Supplier can view the Manager's rules, and interact with it. By doing so, Supplier can book an event on this set.

Let's say that Supplier wants to book 2 hours, from 2018-12-18 10h00 to 12h00. 

* It will split the rule for the like this:
`DTSTART:20181218T070000Z RRULE:BYDAY=TU;FREQ=WEEKLY DTSTART:20181218T070000Z RRULE:BYDAY=TU;UNTIL=20181218T100000Z;FREQ=DAILY DTSTART:20181218T120000Z RRULE:BYDAY=TU;UNTIL=20181218T150000Z;FREQ=DAILY EXDATE:20181218T070000Z`

My idea was to exclude the 2018-12-18 from RRule, with Exdate, and create "single" events where the Manager is still free. From 07h00 to 10h00, and from 12h00 to 15h00. (I've introduced a duration, and the original event goes to 15h00).

Anyway, after calling `rrulestr(event.rules, { forceset: true })`, my object doesn't seem to reflect the String:

```
{
  "_string": null,
  "_cache": null,
  "origOptions": {},
  "options": {
    "freq": 0,
    "dtstart": "2018-12-21T13:09:05.000Z",
    "interval": 1,
    "wkst": 0,
    "count": null,
    "until": null,
    "tzid": null,
    "bysetpos": null,
    "bymonth": [
      12
    ],
    "bymonthday": [
      21
    ],
    "bynmonthday": [],
    "byyearday": null,
    "byweekno": null,
    "byweekday": null,
    "bynweekday": null,
    "byhour": [
      13
    ],
    "byminute": [
      9
    ],
    "bysecond": [
      5
    ],
    "byeaster": null
  },
  "timeset": [
    {
      "hour": 13,
      "minute": 9,
      "second": 5,
      "millisecond": 0
    }
  ],
  "_rrule": [
    {
      "_string": null,
      "_cache": null,
      "origOptions": {
        "byweekday": [
          {
            "weekday": 3
          }
        ],
        "freq": 2,
        "dtstart": "2018-12-20T07:00:00.000Z"
      },
      "options": {
        "byweekday": [
          3
        ],
        "freq": 2,
        "dtstart": "2018-12-20T07:00:00.000Z",
        "tzid": null,
        "interval": 1,
        "wkst": 0,
        "count": null,
        "until": null,
        "bysetpos": null,
        "bymonth": null,
        "bymonthday": [],
        "bynmonthday": [],
        "byyearday": null,
        "byweekno": null,
        "bynweekday": null,
        "byhour": [
          7
        ],
        "byminute": [
          0
        ],
        "bysecond": [
          0
        ],
        "byeaster": null
      },
      "timeset": [
        {
          "hour": 7,
          "minute": 0,
          "second": 0,
          "millisecond": 0
        }
      ],
      "_len": 54
    },
    {
      "_string": null,
      "_cache": null,
      "origOptions": {
        "byweekday": [
          {
            "weekday": 3
          }
        ],
        "until": "2018-12-20T10:00:00.000Z",
        "freq": 3,
        "dtstart": "2018-12-20T07:00:00.000Z"
      },
      "options": {
        "byweekday": [
          3
        ],
        "until": "2018-12-20T10:00:00.000Z",
        "freq": 3,
        "dtstart": "2018-12-20T07:00:00.000Z",
        "tzid": null,
        "interval": 1,
        "wkst": 0,
        "count": null,
        "bysetpos": null,
        "bymonth": null,
        "bymonthday": [],
        "bynmonthday": [],
        "byyearday": null,
        "byweekno": null,
        "bynweekday": null,
        "byhour": [
          7
        ],
        "byminute": [
          0
        ],
        "bysecond": [
          0
        ],
        "byeaster": null
      },
      "timeset": [
        {
          "hour": 7,
          "minute": 0,
          "second": 0,
          "millisecond": 0
        }
      ],
      "_len": 54
    },
    {
      "_string": null,
      "_cache": null,
      "origOptions": {
        "byweekday": [
          {
            "weekday": 3
          }
        ],
        "until": "2018-12-20T15:00:00.000Z",
        "freq": 3,
        "dtstart": "2018-12-20T07:00:00.000Z"
      },
      "options": {
        "byweekday": [
          3
        ],
        "until": "2018-12-20T15:00:00.000Z",
        "freq": 3,
        "dtstart": "2018-12-20T07:00:00.000Z",
        "tzid": null,
        "interval": 1,
        "wkst": 0,
        "count": null,
        "bysetpos": null,
        "bymonth": null,
        "bymonthday": [],
        "bynmonthday": [],
        "byyearday": null,
        "byweekno": null,
        "bynweekday": null,
        "byhour": [
          7
        ],
        "byminute": [
          0
        ],
        "bysecond": [
          0
        ],
        "byeaster": null
      },
      "timeset": [
        {
          "hour": 7,
          "minute": 0,
          "second": 0,
          "millisecond": 0
        }
      ],
      "_len": 54
    }
  ],
  "_rdate": [],
  "_exrule": [],
  "_exdate": [
    "2018-12-20T07:00:00.000Z"
  ]
}
```

I understand that `between()`  doesn't output dates when exclude is set, so I parse the array `ruleSet._rrule` manually to add them in my component, `react-big-calendar`.

The issue that I encounter is DTSTART is wrong in the resulting object from `rrulestr`.

Here's a more graphical representation of this problem:
* Bad:
![image](https://user-images.githubusercontent.com/1532657/50344735-8afc4800-052c-11e9-82f3-8c74dd1415c5.png)

* Expected:
![image](https://user-images.githubusercontent.com/1532657/50344753-a49d8f80-052c-11e9-9b6f-d0a19de7f56c.png)

**Comment by davidgoli** [comment]
This behavior looks correct according to the given string. I see 3 dtstarts:

```
DTSTART:20181218T070000Z
DTSTART:20181218T070000Z
DTSTART:20181218T120000Z
EXDATE:20181218T070000Z
```

2 at 700, and 1 at 1200. You also have an exdate at 7am. To get the "expected" result, I'd expect to see a `DTSTART` at 1300.

`UNTIL` does not specify duration of an event (this library does not have support for event duration), it specifies the "limit of the recurrence", that is, the last date/time on which a recurrence might happen. If you want an event at 1300, you should look at the `RDATE` property for adding one-off dates.

**Comment by MBach** [comment]
Hello @davidgoli 
Thank you for your response. Indeed, I'm using the until as the duration in this very specific case. But how do you explain that the String DTSTART:20181218T120000Z is not reflected in the Javascript object ? (the third one in the array or _rrule).
I'll have a look of `RDATE` if I can adapt this library to my needs.

**Comment by zeluspudding** [comment]
@davidgoli  I'm trying to build a way around rrule not having `duration` / `enddate` support. How would one add a duration in such a way that compensates for daylight savings / the other tricky parts of dates? If you have time / interest in answering my question, I've got it up on [StackOverflow here](https://stackoverflow.com/questions/56615246/add-a-duration-to-a-repeating-events-start-time-so-that-its-end-is-always-the). Thank you in advance
