### ISSUE TITLE
toText translation not all that useful without date formatting

### ISSUE THREAD

**Issue by LosD** [jakubroztocil/rrule#312]
Currently, toText is translatable, but unfortunately the date format is hard coded in totext.ts:
```typescript
...
      this.add(this.language.monthNames[until.getUTCMonth()])
        .add(until.getUTCDate() + ',')
        .add(until.getUTCFullYear().toString())
...
```

Yielding e.g.  `December 14, 2020`, which is a format mostly unused outside USA (https://commons.wikimedia.org/wiki/File:Date_format_by_country.svg), making translating a little bit pointless. E.g. in Danish, this would be `14. december, 2020` (also note the ".", which is the ordinal indicator in Danish, usually used in dates)

Some kind of general date formatting (possibly not bound to the language, e.g. the Brits shares English, but not the date format) would be a giant help around this issue.

(Tested using RRule version 2.5.6, code taken from master)

**Comment by davidgoli** [comment]
The NLP code in this package is expected to be split out into a separate package in v3.0, as localization of that package is a whole ordeal outside of maintaining RRULE itself. I probably won't have bandwidth for this before 3.0, but pull requests are welcome!

**Comment by LosD** [comment]
Makes sense.

A simple "format date" callback in the Language class (with a fallback of "just do as usual") could probably do it for 2.x. I'll see if I can find a bit of time over the weekend.
