### ISSUE TITLE
v2.6.0 produces incorrect output for .between(...)

### ISSUE THREAD

**Issue by viggyfresh** [jakubroztocil/rrule#316]
### Reporting an issue

Hi there! It looks like something has changed in RRule 2.6.0 that causes previously correct output for the `between` API method to just return empty lists. Hopefully this isn't a usage error...

- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [x] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.
    The following snippet produces reasonable output on 2.5.6 but empty arrays on 2.6.0:
    ```
    const options = RRule.parseText('every day');
    const rrule = new RRule(options);
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    console.log(rrule.toText());
    console.log(rrule.between(yesterday, tomorrow));
    ```
- [x] Expected output: `[some dates, at least one, likely 2]`
- [x] Actual output: `[]`
- [x] The version of `rrule` you are using: `v2.6.0`
- [x] Your operating system: macOS 10.13.6
- [x] Your local timezone (run `$ date` from the command line
  of the machine showing the bug): PST

thanks!

**Comment by davidgoli** [comment]
can you verify the same behavior works as expected on a previous version? thanks!

**Comment by davidgoli** [comment]
I'm not reproducing this; I'm seeing 

```
[ 2019-01-15T18:57:07.000Z, 2019-01-16T18:57:07.000Z ]
```

which is the same result I get on v2.5.6.

**Comment by viggyfresh** [comment]
well, derp. let me dig back into this - must have mixed up my experiments or crossed some wires. sorry about that - will report back by the end of the day 😬

**Comment by davidgoli** [comment]
quite alright, I suspect you _are_ seeing something but it may be dependent on some other factor that not all users share - time of day, machine setup, something like that

**Comment by viggyfresh** [comment]
the JSFiddle looks good! I have the exact set of `options` required to cause the issue, here is snippet that actually reproduces the issue:

    ```
    const rrule = new RRule({
        byhour: [0],
        byminute: [0],
        bysecond: [0],
        byweekday: [0, 1, 2, 3, 4, 5, 6],
        count: 0,
        freq: 2,
        interval: 1,
        wkst: 0,
    });
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    console.log(rrule.toText());
    console.log(rrule.between(yesterday, tomorrow));
    ```

I edited your fiddle to produce an empty array in `between`: http://jsfiddle.net/tpdx3skb/3/
I also confirmed that 2.5.6 produces a non-empty array (for real this time)!

Sorry about the miscommunication earlier...looks like I must have overlooked something

**Comment by davidgoli** [comment]
I can tell you why that is, and it's because v2.6.0 fixed a bug where a rule with `count=0` would return more than 0 results. Remove `count: 0` and you'll see it gives a date.

**Comment by viggyfresh** [comment]
Thanks @davidgoli - that was it! Would it be possible to update the release notes to flag this change? Closing the issue in any case.
