### ISSUE TITLE
`before(dt)` doesn't return last occurence when rule object is generated from rrulestr() and the pattern string doesn't have `DTSTART`

### ISSUE THREAD

**Issue by shinhokang** [jakubroztocil/rrule#317]
- [x] The version of `rrule` you are using
v.2.6.0

- [x] Your operating system
Docker image node:8.12.0

- [x] Your local timezone (run `$ date` from the command line
  of the machine showing the bug)
Central European Standard Time

-----

jsfiddle: http://jsfiddle.net/n4Ldz1e0/1/

```
const rule1 = new rrule.rrulestr('FREQ=WEEKLY;BYSECOND=0;BYMINUTE=0;BYHOUR=6;BYDAY=SU');
const rule2 = new rrule.rrulestr('DTSTART:20180311T000000\nRRULE:FREQ=WEEKLY;BYSECOND=0;BYMINUTE=0;BYHOUR=6;BYDAY=SU');
```

here the rule1 and rule2 show different behavior on `before(dt)` function. both returns same result on  `after(dt)`, but `rule1.before(dt)` returns null while `rule2.before(dt)` returns correct occurence.

Does it consider DTSTART as current date time if there's no DTSTART on the pattern string when it parse the pattern?

**Comment by davidgoli** [comment]
That is correct. According to the README for `dtstart`:

> If not given, new Date will be used instead. 

https://github.com/jakubroztocil/rrule#api

**Comment by shinhokang** [comment]
@davidgoli sorry about the misunderstanding. thanks.
