### ISSUE TITLE
Broken in firefox post BST -> GMT switch on 27th October

### ISSUE THREAD

**Issue by SlainVeteran** [jakubroztocil/rrule#32]
On Firefox 24.0 on OSX in Europe/London, following the 27th October (when the DST switch occurs), 1682 tests from http://jkbr.github.io/rrule/tests/index.html fail.  Before the DST switch they all pass.

They all pass fine on Chrome on OSX.

**Comment by arolson101** [comment]
I think this issue is dead.  Please update if more support is needed!
