### ISSUE TITLE
Calculating series with unknown timezones will produce infinite loop

### ISSUE THREAD

**Issue by murjam** [jakubroztocil/rrule#320]
### Infinite loop inside rule iterations when timezone is not an IANA zone

The iterator callback function is never called, `rule.all` just consumes all the CPU.

How to reproduce:
```js
const { rrulestr } = require('rrule');
const rule = rrulestr('DTSTART;TZID=US/Eastern:20181201T020000\nFREQ=WEEKLY;BYDAY=TU\nEXDATE:20190205T020000,20190108T020000');
rule.all(date => {
    // the iterator is never called
    console.log('Will never be printed');
    return false;
});
```

Not exactly sure what are the ingredients of the rule string for this to happen, but for sure the timezone has to be something the luxon library is not aware of. If the timezone in the rule string is an IANA zone, the problem does not arise.

Also seemes to be related to having the EXDATE sometimes.

* rrule version: 2.6.0
* operating system: tested on `node:10-alpine` and `macOS Mojave v10.14.2`
* local timezone: tested on `UTC` and `Europe/Tallinn (EET)`

**Comment by davidgoli** [comment]
I'd welcome a pull request to fix this!

**Comment by procedurallygenerated** [comment]
@murjam @davidgoli 

Is there a solution for this? I would love to help with a pull request am just not technical enough.
