### ISSUE TITLE
RRule accepts "NaN" as a valid interval and causes infinite loop

### ISSUE THREAD

**Issue by TimRobinson1** [jakubroztocil/rrule#321]
The problem arises when a `NaN` value is supplied to the interval and creates `INTERVAL=NaN`.  This happened when coercion was attempted on a non-integer value, and created `NaN` instead.
### Steps to reproduce
```es6
import RRule from 'rrule';

const rrule = new RRule({
  freq: RRule.WEEKLY,
  interval: NaN,
  byweekday: [RRule.MO, RRule.FR],
  dtstart: new Date(Date.UTC(2012, 1, 1, 10, 30)),
  until: new Date(Date.UTC(2012, 12, 31))
})

// DTSTART:20120201T103000Z\nRRULE:FREQ=WEEKLY;INTERVAL=NaN;BYDAY=MO,FR;UNTIL=20130131T000000Z
console.log(rrule.toString());
```
### Actual Results
```
DTSTART:20120201T103000Z\nRRULE:FREQ=WEEKLY;INTERVAL=NaN;BYDAY=MO,FR;UNTIL=20130131T000000Z
```
### Expected Results
```
DTSTART:20120201T103000Z\nRRULE:FREQ=WEEKLY;BYDAY=MO,FR;UNTIL=20130131T000000Z
```
### Additional info
```
macOS Mojave v10.14.2

$ date
Mon 11 Feb 2019 16:50:44 GMT

$ node --version
v8.15.0

rrule version
2.6.0
```

- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [x] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.
- [x] Expected output
- [x] Actual output
- [x] The version of `rrule` you are using
- [x] Your operating system
- [x] Your local timezone (run `$ date` from the command line
  of the machine showing the bug)

**Comment by davidgoli** [comment]
I'd welcome a pull request to fix this!

**Comment by a97001** [comment]
This issue is still happening for current version (2.6.4)
Setting interval to `NaN` or `undefined` will cause infinite loop.
Please review it again.
