### ISSUE TITLE
dayClick event is not working fullcalendar v4 beta?

### ISSUE THREAD

**Issue by patidarkishor777** [jakubroztocil/rrule#324]
Hi 

I am using beta release of the fullcalendar and it seems dayClick event is no working any more, here is my code 
`dayClick: function(date, jsEvent, view) {
        alert('adsada');
  },`

is there any issue with the code?

**Comment by espen** [comment]
This is not the FullCalendar repo. Please try https://github.com/fullcalendar/fullcalendar

**Comment by patidarkishor777** [comment]
> This is not the FullCalendar repo. Please try https://github.com/fullcalendar/fullcalendar

Oops sorry
