### ISSUE TITLE
Question regarding UNTIL in string and timezones

### ISSUE THREAD

**Issue by pezza3434** [jakubroztocil/rrule#331]
I use rrule mainly for the fromString functionality. I take the string given to me by the ICS file, add a timezone to the DTSTART to make use of the rrule timezone functionality and then pass it into rrule.fromString().

My DTSTART is therefore in the relative timezone. All good.

The problem is that the 'UNTIL' time is always provided in UTC time. As far as I can tell this is correct. However because I am using the timezone functionality, this then means that rrule interprets the UNTIL time as in the specified timezone.

For example:

FREQ=WEEKLY;UNTIL=20190424T125959Z;INTERVAL=1;DTSTART;TZID=America/Toronto:20190403T090000Z

This produces four events on the test site. Really it should only produce 3 because T125959Z is UTC time. Therefore in America, the last repeat should not be after T085959. 

At the moment, I'm changing the UNTIL value manually to reflect what I believe is the correct date.

Is this correct? What should I be doing here?

Does that make sense?

I'm really sorry if I'm not being clear. Timezones continue to confuse my programming on a daily basis. This stuff is HARD. I would really appreciate any help on this.

Thank you.

**Comment by davidgoli** [comment]
I don't have the time to troubleshoot this right now, but correct syntax would be:

```
DTSTART;TZID=America/Toronto:20190403T090000
RRULE:FREQ=WEEKLY;UNTIL=20190424T125959Z;INTERVAL=1
```

Note that time with a zone (America/Toronto) should not have a `Z` at the end; I think the `Z` might be overriding the timezone.
