### ISSUE TITLE
EXDATE not working as expected in README example

### ISSUE THREAD

**Issue by froatsnook** [jakubroztocil/rrule#345]
EXDATE doesn't work as I would expect.  The excluded instances are showing up in calls to `all` and `between`.

- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one

- [x] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.

From the README:

```javascript
const rruleSet = new RRuleSet()

// Add a rrule to rruleSet
rruleSet.rrule(new RRule({
  freq: RRule.MONTHLY,
  count: 5,
  dtstart: new Date(Date.UTC(2012, 1, 1, 10, 30))
}))

// Add a date to rruleSet
rruleSet.rdate(new Date(Date.UTC(2012, 6, 1, 10, 30)))

// Add another date to rruleSet
rruleSet.rdate(new Date(Date.UTC(2012, 6, 2, 10, 30)))

// Add a exclusion rrule to rruleSet
rruleSet.exrule(new RRule({
  freq: RRule.MONTHLY,
  count: 2,
  dtstart: new Date(Date.UTC(2012, 2, 1, 10, 30))
}))

// Add a exclusion date to rruleSet
rruleSet.exdate(new Date(Date.UTC(2012, 5, 1, 10, 30)))

// Get all occurrence dates (Date instances):
rruleSet.all()
```

- [x] Expected output

I would expect the occurence 2012-05-01 to not be included in the result of the call to `all`.

```javascript
 [Wed Feb 01 2012 11:30:00 GMT+0100 (Central European Standard Time), Sun Jul 01 2012 12:30:00 GMT+0200 (Central European Summer Time), Mon Jul 02 2012 12:30:00 GMT+0200 (Central European Summer Time)]
```

- [x] Actual output

```javascript
 [Wed Feb 01 2012 11:30:00 GMT+0100 (Central European Standard Time), Tue May 01 2012 12:30:00 GMT+0200 (Central European Summer Time), Sun Jul 01 2012 12:30:00 GMT+0200 (Central European Summer Time), Mon Jul 02 2012 12:30:00 GMT+0200 (Central European Summer Time)]
```

- [x] The version of `rrule` you are using

2.6.0

- [x] Your operating system

macOS Sierra (but the results in the README are also wrong)

- [x] Your local timezone (run `$ date` from the command line
  of the machine showing the bug)

CEST (but the results in the README are also wrong)

**Comment by thefliik** [comment]
> I would expect the occurence 2012-05-01 to not be included in the result of the call to `all`

Months for the Javascript `Date` object are 0 indexed. So the occurrence 2012-05-01 is expressed as `new Date(Date.UTC(2012, 4, 1))`.

It doesn't look like your exclusion rules cover 2012-05-01. A.K.A. this doesn't look like a bug.

**Comment by froatsnook** [comment]
Oh, that's a good point.  Thanks.  Will close for now!
