### ISSUE TITLE
How to load Rrule?

### ISSUE THREAD

**Issue by zeluspudding** [jakubroztocil/rrule#346]
This is a really basic question but I didn't see anyone ask it in the closed issues so I'm going to try - how do you add `rrule.js` to the browser? I've tried adding it in [codepen](https://codepen.io/aagostini/pen/jodVxW?editors=0010) but I just can't seem to get it to work despite trying many different ways of requiring / importing modules.

Namely I keep seeing this error in the console
![image](https://user-images.githubusercontent.com/8431341/58773268-081ef500-8582-11e9-95a9-a1d241829fe6.png)

I even tried loading it in [observable ](https://observablehq.com/@aagostini/rrules)but just couldn't seem to get that working either. Any help is welcome, thanks :)

**Comment by thefliik** [comment]
There are many ways to use rrule in the browser. If you just want to play around  / test rrule in your browser, you can use something like [stackblitz](https://stackblitz.com/) which will allow you to import the module from npm.

You're running into problems because you're trying to import a relative file path ("rrule") from codepen's servers (and, while I've never used codepen, I doubt that codepen has made `rrule` available to it's users in some way). You'd need to import the javascript from a CDN if you're not going to serve it yourself.

**Comment by zeluspudding** [comment]
Hey @thefliik , thank you so much for your comment :) 

stackblitz looks incredible. Codepen is a lot like stackblitz in that it's a playground for building webpages and let's you load scripts from different CDNs. I've loaded my script in through codepen's `settings` dialogue > `Javascript` > then entering the filepath to my hosted script.

![image](https://user-images.githubusercontent.com/8431341/58802023-b7cf8380-85d1-11e9-9f4f-9e2f0b3bbef9.png)

I'm currently hosting rrule at `https://s3.amazonaws.com/appforest_uf/f1559527195623x315562171275647800/rrule.min.js`.

[Here's the updated pen where I'm explicitly loading rrrule](https://codepen.io/aagostini/pen/jodVxW?editors=0010) via a <script> tag but it's still not working - I have the same error as before.

**Comment by zeluspudding** [comment]
So strange, S3 is definitely loading the resource in my console
![image](https://user-images.githubusercontent.com/8431341/58810195-10f3e300-85e3-11e9-9d44-2cc13e320044.png)

As far as I understand there are no other dependencies I need to be loading, right (I tried adding typescript but that didn't seem to matter)?

Had I an npm environment I would copy that lovely stackblitz project you provided but unfortunately I'm limited to client side code only :/

**Comment by zeluspudding** [comment]
According to [Google](https://developers.google.com/web/fundamentals/primers/modules), the file extension can matter on modules.

> A note on file extensions
> You may have noticed we’re using the `.mjs` file extension for modules. On the Web, the file extension doesn’t really matter, as long as the file is served with the JavaScript MIME type `text/javascript`. The browser knows it’s a module because of the type attribute on the script element.

It looks like my files aren't served as `text/javascript` but rather as `application/javascript` or `application/x-javascript`. Anyone here have a hosted version of rrule that delivers it with MIME type `text/javascript`?.. not even https:cdn.jsdelivr.net/npm/rrule@2.6.0/dist/es5/rrule.min.js delivers it that way

**Comment by thefliik** [comment]
Hmm, so I've never had cause to import an ES6 module into the browser directly myself, but it looks like the following code works on codepen:

```javascript
// This imports everything in the `rrule` namespace
import "https://jakubroztocil.github.io/rrule/dist/es5/rrule.min.js"

console.log(rrule)

// Create a rule:
const rule = new rrule.RRule({
  freq: rrule.RRule.WEEKLY,
  interval: 5,
  byweekday: [rrule.RRule.MO, rrule.RRule.FR],
  dtstart: new Date(Date.UTC(2012, 1, 1, 10, 30)),
  until: new Date(Date.UTC(2012, 12, 31))
})
 
// Get all occurrence dates (Date instances):
console.log(rule.all())
```

**Comment by thefliik** [comment]
> So strange, S3 is definitely loading the resource in my console

Maybe you are logged into your amazon account on your computer

**Comment by zeluspudding** [comment]
That's kind of what I was thinking but no, I'm able to access that file from incognito mode and a second computer that doesn't have access. [As seen here](https://codepen.io/aagostini/pen/jodVxW?editors=0010) I've even tried loading the script from [jsdeliver](https://cdn.jsdelivr.net/npm/rrule@2.6.0/dist/es5/rrule.min.js) without luck.

**Comment by thefliik** [comment]
@zeluspudding did you not read my previous comment?

`import "https://jakubroztocil.github.io/rrule/dist/es5/rrule.min.js"` works for me on codepen.

**Comment by zeluspudding** [comment]
Oh, I'm sorry - I did miss your comment. And YES! It does work :)

Thank you sooo much! I really appreciate all the help.

**Comment by zeluspudding** [comment]
For anyone interested in playing with rrule in observable [visit this link](https://observablehq.com/@aagostini/rrule-js).
