### ISSUE TITLE
Timezone Shift of 30 days?

### ISSUE THREAD

**Issue by zeluspudding** [jakubroztocil/rrule#349]
[This timezone example](https://github.com/jakubroztocil/rrule#timezone-support) from the reference page is really curious - seems like there are a lot of errors or I'm very mistaken about how dates work (it's probably the latter)

> ![image](https://user-images.githubusercontent.com/8431341/59052597-0771b180-8855-11e9-8ebd-eee508ad6c6c.png)

Note exhibit `1` and `2`, these dates are in the same year but 30 days apart. I don't believe that timezones ever resulted in a 30 day shift? I suspect the year in exhibit `2` should read `2017` which I've confirmed below using [timeanddate.com](https://www.timeanddate.com/worldclock/converter.html?iso=20180101T013000&p1=248&p2=137&p3=tz_gmt):

> ![image](https://user-images.githubusercontent.com/8431341/59053176-6b48aa00-8856-11e9-9f7f-533596d984d5.png)

- The hour and minute shift between exhibit `2` and `3` are correct since the `17:30` from exhibit `2` corresponds to `5:30 pm` in the timeanddate picture.
- The days in exhibit `1` and `3` should be the same but they aren't.

At first I thought that the year output of exhibit `2` was a typo but no, that's the real rrule output. So I'm thinking that day `02` in exhibit `3` is a typo... _What's going on?_

**Comment by davidgoli** [comment]
Keep in mind that in JS `Date`, months are zero-indexed, not 1-indexed. That means that `Date.UTC(2017, 1, 1, 10, 30, 0)` means February 1, and `Date.UTC(2017, 0, 1, 10, 30, 0)` means January 1.

**Comment by zeluspudding** [comment]
Aha! I thought I'd be wrong, haha. Thanks :)
