### ISSUE TITLE
Unable to select hours/time in demo

### ISSUE THREAD

**Issue by weedkiller** [jakubroztocil/rrule#352]
Hi, the time/hours does not trigger in the demo

![image](https://user-images.githubusercontent.com/21086190/60138479-8b45fc00-9778-11e9-9cd5-3c4334d19fb6.png)

**Comment by davidgoli** [comment]
I'm not able to repro. Based on your screenshot, it looks like your browser is not loading some or all of the CSS or JS. Can you let me know what browser/OS you're using?

**Comment by weedkiller** [comment]
Chrome, I tried online as well and re-cloned to local repo, same issue. Was able to replicate in a diff machine.

**Comment by thefliik** [comment]
FWIW, I am also unable to replicate this issue. Works fine for me using Chrome 75. As `@davidgoli` indicated, the screenshot you shared has strange formatting. It appears the page hasn't loaded properly for you.

What the page should look like:

![Screen Shot 2019-07-10 at 11 22 09 AM](https://user-images.githubusercontent.com/12599934/60994254-07a61680-a305-11e9-82d1-e963462070d9.png)

**Comment by weedkiller** [comment]
Sorry let me clarify

this was a local cloned demo issue, but even in the main demo page, the time picker part does not load... is it expected that `timepicker `this to be manual or with time picker helper

**Comment by thefliik** [comment]
The demo is simply using the native `datetime-local` input type. How it is rendered is dependent on the browser you are using. Google Chrome has a native datepicker, but I do not believe it currently has a native timepicker. This sounds like expected behavior, unless there's another reason you expected otherwise?
