### ISSUE TITLE
RRule is not defined when using the <script> implementation

### ISSUE THREAD

**Issue by brian1037** [jakubroztocil/rrule#353]
Here is a fiddle that replicates the issue. You can see in the network tools that rrule-tz.min.js is being loaded, since it's not obvious in the JSFiddle interface.

https://jsfiddle.net/ogmrkens/

I'm experiencing the same issue on my own website. The snippet I've taken is directly from the documentation, so I'm not sure what I'm doing wrong.

Thank you for any guidance.

**Comment by davidgoli** [comment]
Hi @brian1037 , note that in the script-tag version, the entire package is under the `rrule` namespace, so you'll have to refer to it as `rrule.RRule`. Hope that helps!

**Comment by chriscollins405** [comment]
So im stuck on the same thing, and have used the same fiddle to test....

https://jsfiddle.net/26qou094/1/

I'm including the script tag at the top

Then I have this....

```
import { RRule, RRuleSet, rrulestr } from 'rrule'
const rule = new rrule.RRule({
  freq: RRule.WEEKLY,
  interval: 5,
  byweekday: [RRule.MO, RRule.FR],
  dtstart: new Date(Date.UTC(2012, 1, 1, 10, 30)),
  until: new Date(Date.UTC(2012, 12, 31))
});
```

Which returns....

> Uncaught TypeError: Failed to resolve module specifier "rrule". Relative references must start with either "/", "./", or "../"


Or i try this....

```
const rule = new rrule.RRule({
  freq: RRule.WEEKLY,
  interval: 5,
  byweekday: [RRule.MO, RRule.FR],
  dtstart: new Date(Date.UTC(2012, 1, 1, 10, 30)),
  until: new Date(Date.UTC(2012, 12, 31))
});
```

and get...

> Uncaught ReferenceError: RRule is not defined

What am I doing wrong?
