### ISSUE TITLE
rrule fromString inserting unexpected data into options

### ISSUE THREAD

**Issue by stclairdaniel** [jakubroztocil/rrule#361]
- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one

rrule version: `"rrule": "^2.6.2"`
Operating System: macOS Mojave Version 10.14.6
Local timezone: PDT

Code:
```
const originalString = 'DTSTART;TZID=America/Los_Angeles:19970902T064000\nRRULE:FREQ=WEEKLY;BYDAY=TU;INTERVAL=1;WKST=MO'
const rrule = RRule.fromString(originalString)
const backToString = new RRule({ ...rrule.options }).toString()
```

Expected Result:
backToString should match originalString

Actual Result
`DTSTART;TZID=America/Los_Angeles:19970902T064000
RRULE:FREQ=WEEKLY;BYDAY=TU;INTERVAL=1;WKST=MO;BYHOUR=6;BYMINUTE=40;BYSECOND=0`

Problem: Converting to an rrule using `fromString` adds a `byseconds` , `byminutes` and `byhours` to `options` based on the provided `dtstart`, which become present in the string when we convert back `toString`.

Is this expected, and if so, why? I am building a widget for users to modify existing rrules in a UI and these values are unexpected. I use the spread operator to allow changing any options, like `byweekday` and I need the resultant string to match the original with only the changes that come from the UI. Is this user error or a bad pattern, or a bug in the library?

**Comment by amazingmarvin** [comment]
I am having a similar issue.  I have incoming calendar events with recurrence `FREQ=YEARLY` and a separate start date.  Both `rrulestr` or `RRule.fromString` set `byhour`, `byminute`, `bymonth`, `bymonthday`, and `bysecond` based on the time when the rule is parsed, even if I pass a `dtstart` option to `rrulestr`.  Right now I've worked around this by manually generating `DTSTART` and prepending that to the string I parse.  Anyway, fortunately my app only recurs based on day so the workaround is sufficient, but I can at least confirm that the above happens! :)

**Comment by shaibt** [comment]
There are 2 methods of obtaining (and then overriding) a rule object options in order to create an updated copy:
Using `options` (using example above):

    const byneekdayExample = rrulestr('DTSTART:20190901T110000Z    RRULE:INTERVAL=1;FREQ=MONTHLY;WKST=MO;BYDAY=+3FR')
    const options = { ...byneekdayExample.options, until: new Date() }
    const usesBynweekday = new RRule(options).toString()

results in:

    'DTSTART:20190901T110000Z RRULE:FREQ=MONTHLY;INTERVAL=1;WKST=MO;UNTIL=20201201T082307Z;BYNWEEKDAY=4,3;BYHOUR=11;BYMINUTE=0;BYSECOND=0'

Using `origOptions`:

    const byneekdayExample = rrulestr('DTSTART:20190901T110000Z RRULE:INTERVAL=1;FREQ=MONTHLY;WKST=MO;BYDAY=+3FR')
    const options = { ...byneekdayExample.origOptions, until: new Date() }
    const usesBynweekday = new RRule(options).toString()

Using `origOptions` will only copy the "populated" attributes of the original RRule object into the new one and will not append any unwanted attributes to the resulting string.

This would be result string of using `origOptions`:

    'DTSTART:20190901T110000Z RRULE:INTERVAL=1;FREQ=MONTHLY;WKST=MO;BYDAY=+3FR;UNTIL=20201201T082102Z'

**Comment by stclairdaniel** [comment]
@shaibt you are fantastic! This works perfectly.
