### ISSUE TITLE
Couldn't get it to work

### ISSUE THREAD

**Issue by jones75269** [jakubroztocil/rrule#363]
Maybe i'am silly but i don't get this to work at all. If i include the script its fails in the first line …

I would have looked at the demo page but alle the code there is compressed so it isn't readable. Any hints … are there any dependencies that i am missing?

**Comment by thefliik** [comment]
Demo page source code is here: https://github.com/jakubroztocil/rrule/tree/master/demo

**Comment by espen** [comment]
@jones75269 if you have a specific error please report it. Otherwise you could try Stackoverflow if you have questions about your implementation.
