### ISSUE TITLE
Demo page should import to global/window scope

### ISSUE THREAD

**Issue by mdentremont** [jakubroztocil/rrule#365]
Some libraries such as moment, lodash, etc, expose their goodies to the window, such that when on their webpage, I can drop to a JS console and test stuff out myself (ex: I can use `_` when on the lodash website).

I would be very useful if we could do the same for this library, I've pushed up a pull-request with the appropriate changes.

**Comment by mdentremont** [comment]
@thefliik I actually think both would be great -- I tried the sandbox link, and found myself still wanting to drop to the browser debugger just to try some things out quickly

**Comment by thefliik** [comment]
Fair enough 👍
