### ISSUE TITLE
Question: How can I modify an rrule in an rruleSet instead of adding a new one?

### ISSUE THREAD

**Issue by stclairdaniel** [jakubroztocil/rrule#370]
I could not find anything in the docs.

I see I can add an rrule to an rruleSet by calling rruleSet.rrule(). However, I need to be able to let the user modify the existing rrule, by changing the start time for instance. Is this even possible?

If not, how about removing an rrule from an rruleSet?

**Comment by david-golightly-leapyear** [comment]
Hi, there's not currently a "remove" method on RRuleSet, so I'd recommend doing the following:

1. Using `rruleSet.rrules()`, get a (copied) array of rrules out of the set
2. Remove the rrule you wish to remove from this array
3. Create a new RRuleSet
4. Add the remaining rrules to it

Best of luck!

**Comment by stclairdaniel** [comment]
Thanks for the quick reply! That will work perfectly.
