### ISSUE TITLE
Rule not working as intended. It could be my problem too. New to rrule.

### ISSUE THREAD

**Issue by akspan12** [jakubroztocil/rrule#393]
I am using this string to create a rule  
`DTSTART:20200414T080000Z;RRULE:FREQ=DAILY;INTERVAL=1;UNTIL=20200420T080000Z`
Here is the code snippet.
```
let rruleString = 'DTSTART:20200414T080000Z;RRULE:FREQ=DAILY;INTERVAL=1;UNTIL=20200420T080000Z';
console.log("rule string --->", rruleString);
let rules = rrulestr(rruleString);
console.log("rules -->", rules.all());
```
This rule in English is supposed to mean - 

> "Run daily, 1 time from 14th April till 20th April at 08:00 AM UTC."

But the output of `rules.all()` contain a large number of records. I am not able to understand, where I am wrong. Please help. 
THANK YOU!

**Comment by cmditch** [comment]
rule.all() will get all occurrence dates of a given RRule or RRuleSet, returned as a `Date[]`.

If you're looking for the english description of your rrule, give `rrule.toText()` a go.
