### ISSUE TITLE
Yearly, Monthly, Dayly, Hourly, Minutly, Secondly not working

### ISSUE THREAD

**Issue by IluvatarTheReal** [jakubroztocil/rrule#401]
I have absolutely no idea how its even possible... I was thinking it might have something to do with my computer's time format at some point, but now I'm just at a complete loss.

Here is a picture of the results I get... 

![image](https://user-images.githubusercontent.com/20170466/82601995-63286e00-9b7e-11ea-9a6a-4a0267e6615b.png)

Clearly something is wrong. Everything there seems to be fine and I should have one occurance per day start from may 21 to may 31. The toText function clearly says **every 1 day for 10 times**. The configuration seems good as well...

I get these nonsensical result whenever I use the Yearly, Monthly, Dayly, Hourly, Minutly, Secondly frequency. The only one that seems to be working fine so far is the Weekly frequency.

I even using the RRule string generated from the demo website to make sure I wasn't making a mistake on my side with the configuration of the RRule object, but it gave me the exact same result as in my screenshot.

I'll be happy to provide more information if needed.

The demo website is working fine on every machine I've tried, but the version of RRule I downloaded just seems completely broken on my side.

I'm using the latest version of RRule
Windows 10 OS
Timezone : EST -4 (GMT -04)

**Comment by mateodif** [comment]
+1. It happens to me, too.
