### ISSUE TITLE
Minutely rule (frequency = 1) text typo

### ISSUE THREAD

**Issue by JESUS-PEREZ** [jakubroztocil/rrule#406]
### Reporting an issue

- [X] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [X] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.

_DTSTART:20200617T160200Z↵RRULE:FREQ=MINUTELY;INTERVAL=1;COUNT=3_

- [X] Expected output: **Every minute for 3 times**
- [X] Actual output: **Every minutes for 3 times**
- [X] The version of `rrule` you are using: **v2.6.4**
- [X] Your operating system: **Windows**
- [X] Your local timezone: **Europe/London**

Hello,

There is a typo at the time of building the text for a minutely rule where the frequency is 1.

**Expected output:** every minute for 3 times.
**Actual output:** every minute**s** for 3 times.
**Version:** 2.6.4

I had a look at the source code and I have identified where the issue is. I have tried to create a PR but it is not allowed.

https://github.com/jakubroztocil/rrule/blob/v2.6.4/src/nlp/totext.ts

![image](https://user-images.githubusercontent.com/22843772/84927424-1ed0b500-b0cd-11ea-8eee-f5e835f4ab6f.png)

As you can see in the picture, for hourly rules it is using a different string depending on whether the rule is singular/plural. However, for minutely rule it is always using plural string.

**Comment by tbjgolden** [comment]
was about to create this! nice find

@jakubroztocil

**Comment by jakubroztocil** [comment]
Nice find indeed! I’ll be happy to accept a PR. Ideally with a test case.
