### ISSUE TITLE
(npm)version 2.6.5: without any function file under directory 

### ISSUE THREAD

**Issue by Chiboys** [jakubroztocil/rrule#416]
[###](url) Reporting an issue

Thank you for taking an interest in `rrule`! Please include the following in
your report:

- [ ] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [ ] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.
- [ ] Expected output
- [ ] Actual output
- [ ] The version of `rrule` you are using
- [ ] Your operating system
- [ ] Your local timezone (run `$ date` from the command line
  of the machine showing the bug)

**Comment by zoyun** [comment]
I have the same issue, Module not found: Error: Can't resolve 'rrule' when upgrading to version 2.6.5. There is not any function file when checking node_modules /rrule/.

**Comment by Jogai** [comment]
Now we have to find out on npm that the version is deprecated. It would be better to just push 2.6.6 even if its content would be the same as 2.6.4.

**Comment by Apollon77** [comment]
Yes please release a fixed version. Many projects with the default dep style are broken now.

**Comment by jakubroztocil** [comment]
https://github.com/jakubroztocil/rrule/issues/417#issuecomment-690302884
