### ISSUE TITLE
rrule calculates infinite

### ISSUE THREAD

**Issue by oweitman** [jakubroztocil/rrule#438]
### Reporting an issue

Thank you for taking an interest in `rrule`! Please include the following in
your report:

- [x ] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [ ] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.
- [x ] Expected output
- [ ] Actual output
- [x ] The version of `rrule` you are using
Demo site of rrule testet on 23.11.2020
- [ windows 10 / acutal chrome browser] Your operating system
- [ none] Your local timezone (run `$ date` from the command line
  of the machine showing the bug)

goto https://jakubroztocil.github.io/rrule/
input following parameters
dtstart = 1.1.2020 00:00
tzid = none
until = 31.12.2020
count = 10
interval = 480
wkst = MO
byhour = 5

expected output =
rrule returns empty array

actual output =
rrule loop forever and didnt return anything

**Comment by swapnilnandgave** [comment]
Either pass until or count. Both are not required
