### ISSUE TITLE
what happens when luxon 2.x is released?

### ISSUE THREAD

**Issue by bartvde** [jakubroztocil/rrule#471]
I see that luxon will soon create v2, which will be a breaking change. Will this project move its optional dependency to v2? Are there any plans for that, or not?

**Comment by CrOrc** [comment]
The way luxon is used https://github.com/jakubroztocil/rrule/blob/286422ddff0700f1beb2e65cebff3421cc698aac/src/datewithzone.ts#L36-L41
Used api is compatible with luxon v2

**Comment by bartvde** [comment]
can we then update the optional dependency to accept 2.x as well?

**Comment by davidgoli** [comment]
The dependency on Luxon has been removed in 2.7.0.
