### ISSUE TITLE
Timezone offset incorrect with RRule when rule created before timezone changes

### ISSUE THREAD

**Issue by Will-Mann-16** [jakubroztocil/rrule#480]
Rrule version: 2.6.8
MacOS
BST Timezone
`        

	if (item.rrule) {
    	      const repetitions = (item.rrule as RRule).between(rangeStart.toJSDate(), 		rangeEnd.toJSDate(), true);
	          const duration = end.diff(start);
	
    	      repetitions.forEach((rep) => {
        	    const newStart = DateTime.fromJSDate(rep).toUTC();

            	acc.push({
              	start: newStart.toJSDate(),
              	end: newStart.plus({ seconds: duration.as('seconds') }).toJSDate(),
            	});
          	});
        	}
`

So my issue is, if I've created a recurring event in my calendar before the timezones changed (GMT) for the UK, then when they switched to BST, the time is offset by an hour.

Is currently: Sat, 28 Aug 2021 08:00:00 GMT
Should be: Sat, 28 Aug 2021 08:00:00 BST

**Comment by LuisaMontanez** [comment]
Hi @Will-Mann-16 
Did you find a solution for this? I am facing this same issue 😞

**Comment by davidgoli** [comment]
@Will-Mann-16 @LuisaMontanez This is behaving as expected. Please read https://github.com/jakubroztocil/rrule#important-use-utc-dates
