### ISSUE TITLE
unsupported RRULE parm: X-BUSYMAC-REGENERATE=TRASH

### ISSUE THREAD

**Issue by mikeyyyzhao** [jakubroztocil/rrule#482]
Getting an error: `unsupported RRULE parm: X-BUSYMAC-REGENERATE=TRASH`, has anyone seen this error before?

**Comment by davidgoli** [comment]
That simply indicates that `X-BUSYMAC-REGENERATE` is not a supported RRule param. Exclude it from the object you are passing in to the `RRule` or `RRuleSet` constructor.
