### ISSUE TITLE
Github release number and Yarn version number out of sync

### ISSUE THREAD

**Issue by therden** [jakubroztocil/rrule#485]
The _Releases_ section of the `<> Code` page for this **rrule** Github repo identifies **2.6.6** as the latest release, but the [Yarn repository](https://yarnpkg.com/package/rrule) identifies **2.6.8** as the current version.

([The February 4th commit](d901ba9dc71e378138ed78fcbce269618dd30d58) by @davidgoli bumps **rrule**'s version to **2.6.8** -- but that commit hasn't yet been incorporated into an actual release.)

**Comment by jonraedeke** [comment]
A release would be useful for getting assets easily via Composer in Drupal as well.

**Comment by therden** [comment]
Thank you @davidgoli.  

Would you or @jakubroztocil be able to offer a guess as to when a new Release of this library will be made available?  

22 months have passed since the advent of v.2.6.6...

**Comment by davidgoli** [comment]
We released 2.7.1 yesterday.

**Comment by davidgoli** [comment]
Ah yes. That page is currently a manual process, not tied to the actual npm version available. I'll update this now, but please use npm as the source of truth going forward: https://www.npmjs.com/package/rrule
