### ISSUE TITLE
RFC 5545

### ISSUE THREAD

**Issue by Keytwo** [jakubroztocil/rrule#49]
Hello, 

any plan to support the new RFC? http://tools.ietf.org/html/rfc5545
I need to get result RRULE string to be parsed with a library that uses this more recent version of the specification that differs slightly from the one you are using.

Thanks in advance and keep doing the good work ;)

**Comment by espen** [comment]
Some differences are noted in [the readme](https://github.com/jakubroztocil/rrule#differences-from-icalendar-rfc). For any other differences or missing support please open a specific issue.
