### ISSUE TITLE
npm build fail? Requires changes to `import` to fix.

### ISSUE THREAD

**Issue by ogrotten** [jakubroztocil/rrule#505]
rrule 2.6.9 (`"rrule": "^2.6.9",` from package.json)
SvelteKit (`"@sveltejs/kit": "next",`)

This failure occurs on both Github Actions as well as local Ubuntu 20.04 (Win 11 WSL2) 

Local message: 
```
> Using @sveltejs/adapter-static
file:///[..private path..]/.svelte-kit/output/server/chunks/SeriesForm-e75ff8dd.js:4
import { RRule } from "rrule";
         ^^^^^
SyntaxError: Named export 'RRule' not found. The requested module 'rrule' is a CommonJS module, which may not support all module.exports as named exports.
```

This is fixed by making the following change 

original import 
```
import { RRule, RRuleSet, rrulestr } from 'rrule'
```
working import
```
import pkg from 'rrule';
const { RRule } = pkg;
```

Was this expected? Did I miss a doc/announcement?

**Comment by davidgoli** [comment]
Please update to 2.7.0 and let me know if you're still having problems.
