### ISSUE TITLE
Parse and transform cron expressions

### ISSUE THREAD

**Issue by jgornick** [jakubroztocil/rrule#51]
When you want to use rrule with another library that schedules jobs to run, they use cron expressions. It'd be nice to convert an rrule to a cron expression.

**Comment by jpmckearin** [comment]
Does anyone else have any ideas on how one might go about doing this? I looked at cron-parser as suggected by @jkbrzt but it simply parses cron string into "intervals" that you can iterate through. I don't see how that could be particularly useful in this feat. I'm having a hard time coming up with any solutions to the iCal -> cron conversion we're looking for.

**Comment by cdaringe** [comment]
@jpmckearin @jakubbroztocil @jgornick, did you find anything?  Where'd you land?

**Comment by jpmckearin** [comment]
Sorry @cdaringe I am afraid I can't be of much help. Soon after this we moved to using all cron to get around conversion issues.

**Comment by cdaringe** [comment]
thanks @jpmckearin. for others, i did find [_this_](https://jira.terracotta.org/jira/browse/QTZ-252).  it looks pretty promising as something that takes `RRule`s as input and _does something_ on rule ticks.  its not quite what this thread was all about, but close enough.  Olivier's code wasn't merged, but it looks moderately robust and tested from a cursory view :)

**Comment by jacktuck** [comment]
I think the main blocker is that RRULE is much more granular than cron -- or at least i've found that to be the case, correct me if i'm wrong.

**Comment by arolson101** [comment]
I think this issue is dead.  Please update if more support is needed!
