### ISSUE TITLE
Switch from faux-ESM to real ESM exports

### ISSUE THREAD

**Issue by karlhorky** [jakubroztocil/rrule#512]
### Reporting an issue

Thank you for taking an interest in `rrule`! Please include the following in
your report:

- [x] Verify that you've looked through existing issues for duplicates before
  creating a new one
- [x] Code sample reproducing the issue. Be sure to include all input values you
  are using such as the exact RRule string and dates.
- [x] Expected output
- [x] Actual output
- [x] The version of `rrule` you are using `2.7.0`
- [x] Your operating system `macOS Monterey 12.4`
- [ ] Your local timezone (run `$ date` from the command line
  of the machine showing the bug)

The `"module"` field in `package.json` is non-official, and not a real ESM specification of npm: https://stackoverflow.com/a/42817320/1268612

Switching away from `"module"` to use the `"exports"` and `"type": "module"` fields in the `package.json` would allow for better compatibility with ESM, everywhere it is used.

You may even consider making it a pure ESM package, as mentioned here: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

Expected output (see `"type"` and `"exports"` fields):

```bash
$ cat node_modules/rrule/package.json
{
  "name": "rrule",
  "version": "2.7.0",
  ...
  "main": "dist/es5/rrule.js",
  "type": "module",
  "exports": "./dist/esm/src/index.js",
  "types": "dist/esm/src/index.d.ts",
  ...
}
```

Actual output (see the outdated faux-ESM `"module"` field):

```bash
$ cat node_modules/rrule/package.json
{
  "name": "rrule",
  "version": "2.7.0",
  ...
  "main": "dist/es5/rrule.js",
  "module": "dist/esm/src/index.js",
  "types": "dist/esm/src/index.d.ts",
  ...
}
```

**Comment by davidgoli** [comment]
Thanks for the suggestion. I don't think we're ready to abandon cjs users at this point, especially considering how new ESM is to Node itself, but I would like to improve the ESM support. What do you think about a solution like the one outlined here: https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1

**Comment by karlhorky** [comment]
Maybe it would work, I've heard some (rare) accounts of projects providing both ESM and CJS successfully. Any kind of improvement would be great! 👍

**Comment by davidgoli** [comment]
Please take a look at the latest (2.7.1) and let me know how it's working for you now

**Comment by karlhorky** [comment]
@davidgoli thanks for the new version!

`rrule` is still not published as ESM.

Importing and using `rrule` in the following file (import copied from the readme) leads to an error.

`index.mjs`

```js
import { RRule } from 'rrule';

console.log(RRule);
```

The error is this below:

```bash
node index.mjs
file:///Users/k/p/ical-move-events/index.mjs:1
import { RRule } from 'rrule';
         ^^^^^
SyntaxError: Named export 'RRule' not found. The requested module 'rrule' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'rrule';
const { RRule } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

Luckily there is a workaround and it is printed out in the error message, but a lot of users will probably not notice it or not understand:

```js
import pkg from 'rrule';
const { RRule } = pkg;

console.log(RRule);
```

So probably this issue should be reopened, for seamless real ESM support.

**Comment by karlhorky** [comment]
@davidgoli do you think you could reopen this issue? I think it is not resolved yet.

**Comment by karlhorky** [comment]
@davidgoli I'll open a new issue for this and link to it here instead.

**Comment by JuicyZest** [comment]
Same Issue here, 
import pkg from 'rrule';
const { RRule } = pkg;
This workaround resolves the module error, but gives me a RRule is not a constructor error when trying to create a new RRule object.
Anyone ever found a solution ?

**Comment by karlhorky** [comment]
@JuicyZest this issue is closed, can you copy your comment above to the current issue over here?

- #548
