### ISSUE TITLE
regression in 2.7.0

### ISSUE THREAD

**Issue by dereekb** [jakubroztocil/rrule#521]
I tried updating to 2.7.0 directly it caused some of my tests to fail, so some unintended behaviors may have changed between the two versions.

I can't dig too deep into the issue right now, but wanted to raise it just to let you know there is a difference, and I didn't see anything posted about intentional differences. Here's the failure on my CI and the test it was running:

failed tests:
https://app.circleci.com/pipelines/github/dereekb/dbx-components/797/workflows/5a33c0bd-ee90-48ca-9cac-fa2a06a66d21/jobs/1917/tests#failed-test-1

test run:
https://app.circleci.com/pipelines/github/dereekb/dbx-components/797/workflows/5a33c0bd-ee90-48ca-9cac-fa2a06a66d21/jobs/1917/parallel-runs/0/steps/0-106

```
  ● DateRRuleUtility › DateRRuleInstance › expand() › timezone shifting › (Denver to Los Angeles Time) › mo,we,th at 11AM-12PM (1PM-2PM CST) 3 times › with range › it should return only the first date if start and end date equals first date

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      55 |
      56 |                 expect(results.between).toBeDefined();
    > 57 |                 expect(results.dates.length).toBe(expectedResults.length);
         |                                              ^
      58 |                 expect(results.dates[0].startsAt).toBeSameSecondAs(expectedExpandResults[0]);
      59 |               });
      60 |             });

```

Here's the tests being run.
https://github.com/dereekb/dbx-components/blob/4b0699c411f04d08982947f981993a87edbe2b46/packages/date/src/lib/rrule/date.rrule.spec.ts#L58

I run these tests in several different timezones too. The first test that failed was using TZ=America/New_York, but I imagine it is failing for the other timezones as well.

It looks like it is not returning a date that was being returned previously. Another test is failing with some expected dates being an hour off, another one 4 days off.

I'd check that the rrule tests are capturing that test case in particular and see if you're getting your expected output.

### Reporting an issue

Thank you for taking an interest in `rrule`! Please include the following in
your report:

- [x] Verify that you've looked through existing issues for duplicates before
      creating a new one
- [x] Code sample reproducing the issue. Be sure to include all input values you
      are using such as the exact RRule string and dates.
- [x] Expected output
- [x] Actual output
- [x] The version of `rrule` you are using
- [x] Your operating system
- [x] Your local timezone (run `$ date` from the command line
      of the machine showing the bug)

rrule 2.7.0
macOS Monterey 12.2
Date: Thu Jun  9 18:06:30 CDT 2022

**Comment by davidgoli** [comment]
Hi @dereekb , thanks for letting us know, and thanks for the test case; we'll look into this.

**Comment by davidgoli** [comment]
@dereekb Can you please work up a minimal repro using _only_ the rrule library? I will have limited time to do this myself in the next couple of weeks, and hope to troubleshoot sooner.

**Comment by dereekb** [comment]
I will, but probably not in the immediate. Not using the date modules that extensively right now either (and not looking forwards to debugging timezones again), but should be in a few weeks.

Mainly just wanted to ping that there was a regression with the returned results with just a version bump, and make a thread incase anyone else came across the behavior. A majority of my tests still pass, so it could just be an edgecase.

**Comment by dereekb** [comment]
Ok, yea it was a me issue. I didn't have Luxon installed prior, so the tzid input (that was being incorrectly passed) was being ignored.

With the new changes it was no longer being ignored since the new tzid handling changes were implemented. All good now!
