### ISSUE TITLE
Feature: exception rule

### ISSUE THREAD

**Issue by brendan-pike** [jakubroztocil/rrule#594]
I'm new to rrule so might be missing an existing ability.  I'm trying to recreate a meeting pattern our group uses.
We meet on every Saturday except for the first Saturday of each month.
So far I can't see a way to create this recurring rule, if so an exception rule would be useful, ie. except the first sat. of each month.

**Comment by davidgoli** [comment]
See `RRuleSet.exrule`

**Comment by brendan-pike** [comment]
Thank you
