### ISSUE TITLE
Subsumption of rules

### ISSUE THREAD

**Issue by aramk** [jakubroztocil/rrule#64]
Great library! I was wondering if it's possible to determine whether one rule subsumes another - that is, whether the recurrence of one rule is a superset of the recurrences of another rule. A simple example could be:

Rule 1: Every monday, wednesday and friday of every week at 9:00am.
Rule 2: Every day of every week at 9:00am.

Here Rule 2 subsumes Rule 1.

A naive approach would be to determine what the period of the recurrence is (e.g. Rule 1 is 1 week, Rule 2 is 1 day) and check whether the rule of longer period can have all recurrences reproduced using the rule of shorter period. A better approach is to deterministically compare the rules. I think a rule subsumes another if:
- `freq` must be >=
- `interval` must be <=
- `dtstart` must be equal or earlier
- `byweekday` set of days must be equal or a superset

I'm solving a related problem in my app but I might need this later on. If so I might end up implementing it.

**Comment by espen** [comment]
Seems like you want some custom solution and it is not covered by [RFC5545](https://tools.ietf.org/html/rfc5545)
