### ISSUE TITLE
IE8 support broken in 2.1

### ISSUE THREAD

**Issue by dustinsmith1024** [jakubroztocil/rrule#74]
Just noticed IE8 support was broken when the underscore dependency was removed.  This is fine, it'd just be nice to have the doc's or changelog updated to make that clear.

I downgraded to 2.0.0 and it seems to work fine right now.  We will probably added in a ES5 Shim and upgrade shortly.

**Comment by arolson101** [comment]
I think this issue is dead.  Please update if more support is needed!
