### ISSUE TITLE
toText does not display the bysetpos values

### ISSUE THREAD

**Issue by domarmstrong** [jakubroztocil/rrule#75]
```
RRule.fromString('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=2,-1').toText();
// every month on Monday
```

But it should output something like `every month on the second and last Monday`

**Comment by diosney** [comment]
+1 Same here.

**Comment by NaWer** [comment]
+1
ByDay can achieve the same result :
```javascript
RRule.fromString('FREQ=MONTHLY;BYDAY=+2MO,-1MO').toText();
// every month on the 2nd Monday and last Monday
```

**Comment by jakubroztocil** [comment]
The support is incomplete ([as mentioned here](https://github.com/jakubroztocil/rrule#natural-language-text-methods)), but there should be a warning in the string returned by [`toText()`](https://github.com/jakubroztocil/rrule/blob/ffe55016de9ce5ba49680fc3d891fd24f5ea0f90/lib/nlp.js#L178-L215) that the textual representation is approximate. 

It looks like [`isFullyConvertibleToText()`](https://github.com/jakubroztocil/rrule#rruleprototypeisfullyconvertibletotext) is broken and always returns `true`.

```js
r = RRule.fromString('FREQ=MONTHLY;BYDAY=MO;BYSETPOS=2,-1')
r.isFullyConvertibleToText()
true  // Should be false
```

**Comment by rameshsrinivasan** [comment]
+1 Same here.

**Comment by rameshsrinivasan** [comment]
I have fixed this issue.
Please find below lines.

             if(typeof options.bysetpos != 'undefined' && options.bysetpos != '') {
                n = Number(options.bysetpos)
                wday = day;
                wday = RRule[wday].weekday
                options.byweekday.push(new Weekday(wday, n))
              } else {
                wday = RRule[day] // wday instanceof Weekday
                options.byweekday.push(wday)
              }
Line Number 1331 (rrule.js file)
https://github.com/rameshsrinivasan/rrule/blob/master/lib/rrule.js#L1331

**Comment by rameshsrinivasan** [comment]
I have added for only BYSETPOS, U can use it and fix it accordingly.

**Comment by jungalwala** [comment]
+1
I have the same issue.
