### ISSUE TITLE
No support for week number in monthly recurrence?

### ISSUE THREAD

**Issue by DMeganoski** [jakubroztocil/rrule#85]
Standard recurrence have the option to specify a week number for a monthly recurrence. Creating such a recurrence in Google calendar provides an RRule such as this for the first Wednesday of the every month

`FREQ=MONTHLY;BYDAY=1WE;INTERVAL=1`

From what I can tell, there is no support for this, although I do see `this.byweekday.someWeeks` in nlp.js, which seems to perhaps be this support, though I cannot figure out how to modify this property to get it to work correctly.

Any help would be much appreciated.

**Comment by jakubroztocil** [comment]
I think you're looking for `bysetpos`:

[FREQ=MONTHLY;BYDAY=WE;BYSETPOS=1](http://jakubroztocil.github.io/rrule/#/rfc/FREQ=MONTHLY;BYDAY=WE;BYSETPOS=1)

**Comment by DMeganoski** [comment]
That did the trick! RRule specifications are not very well documented. Thank you.
