### ISSUE TITLE
predicate function as well as iterator function as options to `all` and `between`.

### ISSUE THREAD

**Issue by alexcoady** [jakubroztocil/rrule#89]
Currently the iterator function can only be used to completely break the loop. It would be tremendously useful to also be able to pass a test to see whether to add the current date to the returned list.

`var dates = rruleObj.all( iteratorFn, predicateFn );`

This would allow the loop to continue after finding a result you didn't want returned, for whatever reason, rather than halting the entire process, especially as there's no way to just jump in at a certain index.

**Comment by miguelcobain** [comment]
:+1: 

Finding the nth occurrence of the rrule would be extremely useful. As well as to test if a certain date matches an rrule.

**Comment by davidgoli** [comment]
@miguelcobain you can find the nth occurrence of a rule like so:

```js
const rrule = new RRule('...')
const nthRecurrence = rrule.all((_, i) => i === n).pop()
```

A pull request for a predicate function would be welcome.
