### ISSUE TITLE
Output does not match required input

### ISSUE THREAD

**Issue by bsaverino** [jakubroztocil/rrule#98]
The output of rrule creates WKST=6;FREQ=HOURLY;DTSTART=20150512T144523Z;INTERVAL=4;BYHOUR=15;BYMINUTE=36;BYSECOND=23

If you plug this into [your demo](http://jakubroztocil.github.io/rrule/) you get an error.  If you change `WKST=MO` it will display an output. 

If you enter `WKST=SU` it breaks the browser for some reason.

**Comment by bsaverino** [comment]
To add a little more clarity, the output is being created with `RRule.optionsToString(rule.options)`

**Comment by espen** [comment]
Closing in favour of https://github.com/jakubroztocil/rrule/issues/187 WKST should be weekday string (MO) not integer.
